### ISSUE TITLE
add ops:Tracking_Meta/ops:archive_status to meta section of API response

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#101]
## 💡 Description

Per https://github.com/NASA-PDS/registry-api/issues/466, need this added to API spec and implementation.

**Comment by tloubrieu-jpl** [comment]
@al-niessner @jordanpadams I am wondering why ther tracking_meta and ops:data_files are arrays in the API response, see for example, with request `curl --location --request GET 'http://localhost:8081/products/urn:nasa:pds:insight_rad::2.1' \
--header 'Accept: application/vnd.nasa.pds.pds4+json'`

 ```
      "ops:Data_Files": [
            {
                "ops:file_name": "readme.txt",
                "ops:file_ref": "/data/readme.txt",
                "ops:creation_date": "2020-01-03T17:58:09Z",
                "ops:file_size": "1114",
                "ops:md5_checksum": "192de32c12437c180a9e14d60fe4b89a",
                "ops:mime_type": "text/plain"
            }
        ],
        "ops:Tracking_Meta": [
            {
                "ops:archive_status": "archived"
            }
        ]
```

The label file info is not an array:
```
"ops:Label_File_Info": {
            "ops:file_name": "bundle_insight_rad.xml",
            "ops:file_ref": "/data/bundle_insight_rad.xml",
            "ops:creation_date": "2020-01-15T17:40:30Z",
            "ops:file_size": "6805",
            "ops:md5_checksum": "adfd86bbf2573c37d862e27e08f332db"
        },
```

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

I did not change the Data_Files or Label_File_Info (that I remember) so they should how they are not because of me but because of how they have always been. I simply cut-n-pasted tracking service from data files. If you want to change them, it is pretty simple but do you want to do it in this ticket or another?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams says that should be a dictionnary

**Comment by jordanpadams** [comment]
should be Data_Files is array, Tracking_Meta is dictionary:

     "ops:Data_Files": [
           {
               "ops:file_name": "readme.txt",
               "ops:file_ref": "/data/readme.txt",
               "ops:creation_date": "2020-01-03T17:58:09Z",
               "ops:file_size": "1114",
               "ops:md5_checksum": "192de32c12437c180a9e14d60fe4b89a",
               "ops:mime_type": "text/plain"
           },
           {
               "ops:file_name": "readme2.txt",
               "ops:file_ref": "/data/readme2.txt",
               "ops:creation_date": "2020-01-03T17:58:09Z",
               "ops:file_size": "1114",
               "ops:md5_checksum": "192de32c12437c180a9e14d60fe4b89a",
               "ops:mime_type": "text/plain"
           }
       ],
       "ops:Tracking_Meta": {
               "ops:archive_status": "archived"
       }

**Comment by jordanpadams** [comment]
@tloubrieu-jpl where are we at with this?

**Comment by jordanpadams** [comment]
@al-niessner ☝️

**Comment by tloubrieu-jpl** [comment]
I've tested that successfully with format pds4+json on main branch today.
