### ISSUE TITLE
lidvid resolution need to use _search instead of _doc elasticsearch requests 

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#105]
## 💪 Motivation
1. _doc is about to be deprecated
2. it is does not support the Cross Cluster Search (CCS) which is needed for the production deployment

## ⚖️ Acceptance Criteria
**Given** a registry setup with 2 opensearch servers and CCS configured
**When I perform** a request on /products/<lidvid>
**Then I expect** I expect to get the response wherever the lidvid is stored (on ant of the 2 opensearch)

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Two items:

1. Which lidvid resolution? There are at least two and maybe more as I have not completely combed the code for all variants looking for lidvids in the database.
2. Cannot find `_doc` nor `doc_`, latter is to verify not a typo, in the code so not sure what `_doc` means with respect to current implementation.
```
registry-api$ find . -type f -exec grep doc_ {} \; -print
registry-api$ find . -type f -exec grep _doc {} \; -print
registry-api$ 
```

**Comment by tloubrieu-jpl** [comment]
That should be fixed with the latest version of the registry-api.

@jimmie  will see if the error can be reproduced with opensearch and the latest API as about to be merged in https://github.com/NASA-PDS/registry-api/pull/104

**Comment by al-niessner** [comment]
@jimmie 

I found two more threads of lidvid look up that did not use search. I rerouted and removed them. Everything should use search now on PR #112 

Sorry about that, but thought I had found them before. I am successful this time...

```
registry-api$ find . -name \*.java -exec grep GetRe {} \; -print
registry-api$
```

**Comment by tloubrieu-jpl** [comment]
@jimmie still needs to test that

**Comment by jimmie** [comment]
Preliminary tests show that Al's initial efforts were effective. Once PR#112 is merged and a release is cut, I will test out the other areas he recently fixed.

**Comment by jimmie** [comment]
Looks good.
