### ISSUE TITLE
documentation does not match behavior

### ISSUE THREAD

**Issue by al-niessner** [NASA-PDS/registry-api#106]
## 🐛 Describe the bug
Start at the top (documentation)  with a review that it meets all desirements and requirements. Once documentation is reviewed, verify implementation matches.

## 📜 To Reproduce
Pick any endpoint that specifies a lidvid for a single result and the result includes a summary but the documentation claims it should not happen.

## 🕵️ Expected behavior
Documentation should define expected behavior and implementation should meet it.

## 📚 Version of Software Used
At and after commit 0e33c06

---

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

First item from documentation comes in five parts about parameter consistency:

1. All endpoints should support the parameter fields
2. All endpoints that return more than one result should support the parameters start, limit, sort, summary only.
3. All endpoints that do not have an identifier should support the parameters q and keyword
4. ~~all/latest should be an enumerated parameter rather than node because it modifies the behavior with a default behavior like all of the other parameters~~
5. stati or status should be an enumerated parameter on all endpoints with a default of archived,certified to take it out configuration and give it back to the user.

**Comment by al-niessner** [comment]
Number 4 is wrong. Latest or all changes the parameters to control it.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner ,

Thanks for going through that.

My comments:
1. that would be a nice-to-have but I don't feel like it is critical for end-points returning a single result. That would not work on pds4-like response format as well.
2. ok
3. ok
4. We discussed that topic with the working group and internally with the dev team, there is a slide deck which shows options which were proposed https://docs.google.com/presentation/d/1b2Yz2zeIhtPpbXYY8xOT23xhBmk4oLFIEKVrlBUo1Ds/edit#slide=id.ge554174f2e_0_32 the one implemented is the one validated by the group. We can discuss that again if you have concerns on that, but I see that you crossed it so, we can say it's good.
5. status is not a parameter of the url because it is not a criteria we want to expose to users but we want the administrator to use it to filter what the users are allowed to see. For this reason the criteria is implemented in the application.properties. Does this make sense ?

Thanks,

Thomas

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Simple one, the SNAPSHOT-1.0.0 on swaggerhub (Yeah it is working for me today) does not match that on main branch this repo. Which is correct?

Oh yeah, the version on swaggerhub is showing it has an error as well.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Sorry but explaining 5 in detail is going to take some writing. It will be in the form of a scenario followed by outcomes then consequences of those outcomes.

Let us say we have 3 people Amy, Bob, and Cathy. Bob was working with Cathy on lidvid urn:fubar:snafu:13.0 and Bob noticed some things for Amy to work on and noted it was version 13.0 of a fubar collection. Amy then uses the /products to find the item Bob wants reviewed and maybe modified. However there are no version 13 results for fubar. They both go back to Cathy to get the exact lidvid and now it shows up. Here are the possible outcomes because the track filtering is hidden and not consistent on all endpoints:

1. All three just write off that registry-api does not really work but ignore it
2. All three are annoyed that something simple took so much effort and report it as a bug.
3. Cathy has done this before and has to explain the super secret filtering process. Some debate then report it as a bug to try and get it fixed.
4. Cathy has done this before and has to explain the super secret filtering followed by silence.

Consequence of the outcomes:

1. registry-api gets the reputation of not being well done, broken, or just not worth it. It is the only consequence where the desire to hide the status is not revealed. Another possibility is that the annoyance continues to grow until outcome 2, 3, or 4 is realized.
2. Once reported as bug there are two options. First, disseminate the secret information to show that it is a feature not a bug -- something that is often more humorous than real. Still the secret is out. Second, is to make status available to the user or apply the filter uniformly on all endpoints (fix what Amy, Bob, and Cathy view as a bug).
3. Since Cathy has been let in on the secret, the secret is passed as gossip accumulating errors as it goes. As above, a push is made to fix it by allowing the user to have some control over the filter process or make it uniform on all endpoints.
4. Since Cathy has been let in on the secret, the secret is passed as gossip accumulating errors as it goes. Silence of the secret only enshrines its gossip nature causing its ever widening circle for those that want to be in on the know.

In all cases, the internals of the DB will not be hidden or secret for very long. It will either be from those that know a lidvid and want to see it despite its status -- presumably why specific identified endpoints do not filter -- if all endpoints always apply the filter or because people search for things that do not show up but are found when explicitly identified. Therefore the argument for keeping it way from the user is to hide internal details is a fallacy.

If the desire is keep the actual states like archived, certified, and staged private because they may change in the future that is fine. It is not the actual states the user should have control over just the filtering process. Therefore a simple ignore_status being true/false would be sufficient to know when to filter or not and assign it a default of false for all endpoints. What states to filter on would then be in the configuration. Each endpoint behaves consistently. The user can predict the behavior. The user can choose the desired behavior.

Second advantage is that with control back to the user, some documentation would have to be written to explain the process and filtering. The gossip dies.

**Comment by jordanpadams** [comment]
@al-niessner so think if i understand the concern, you are saying we should allow a user to be able to turn off filtering and get all of the data regardless of archive status, e.g. turn off the filter and get all of staged, certified, archived, etc. data.

if that is the point you are trying to make, our requirement differs from that. the point of the API is that archive status designates data this is open to the public (archived, certified, some_future_foo_status) vs. data that is restricted to admin, or login-required access. so we can create the new search parameter you are talking about, but I think we will need to table this until the next build in order to support login-access for the restricted data.

does that make sense?

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

No, what I am saying is that archive status is not being filtered uniformly and seemed wrong for the reasons I stated. For instance, /products does the filtering but /product/{identifier} does not. My example was the confusion it would cause if the idea was to keep the archive status secret (previous conversations). You have stated it is for access control making the filtering non-uniformity even a bigger problem. If there are reasons to show anonymous only fubar and not snafu based on archive status then if anonymous guesses or obtains a LIDVID of snafu then they can use /products/{identifier} to access snafu rather than being prevented breaking your stated goal/requirement/desirement.

The long this stays on hold, the more time/effort it will take to fix.

**Comment by jordanpadams** [comment]
@al-niessner got it! We need to fix this. We should only allow access to the "public" data at every endpoint. i will create a ticket to fix this.

**Comment by tloubrieu-jpl** [comment]
+1 Right, sorry I missed that during the testing. Thanks Al for catching that

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

As requested at the breakout documenting the problem here for everyone's perspective.

The 3 distinct /bundles, /collections, and /products all return a list of the what the name implies. The interesting part is the /products/{identifier} with a product lidvid it returns the product. Using a collection or bundle lidvid with the /products returns the collection and bundle as well. The documentation makes it clear that bundles and collections are also products so that they are returned with /products as well as with /products/{identifier}

The odd part is /bundles/{identifier} or /collections/{identifier} with a product lidvid it returns the product. This is odd because /bundles and /collections do not return products nor collections or bundles respectively. So if /bundles and /collections is meant, as I read them, to return only bundles and collections respectively then should not /bundles/{identifier} and /collections/{identifier} also be equivalently restrictive?

If not then can the redundancy be reduced by having only /products/{identifier} since they all behave the same anyway?

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Another issue. There is /bundles/{id}/collections, /bundles/{id}/collections/latest, /bundles/{id}/collections/all. Similarly, there is /bundles/{id}/products but there are not latest and all. Omission (error) or expected?

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Another thought: limit=0 in lieu of summary-only=true?
