### ISSUE TITLE
Remove the home controller from the swagger-ui

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#108]
## 💪 Motivation
...so that it does not interfere in the user's mind with the actual API end-points. There might also be security issues with the exposure of this end-point.

## 📖 Additional Details

![Screen Shot 2022-03-24 at 10 11 34 AM](https://user-images.githubusercontent.com/60993872/159972784-fd72536f-2670-4d48-9844-9cdb6b3d97c7.png)

## ⚖️ Acceptance Criteria
**Given** a deployed registry API
**When I perform** http:<deployed server>
**Then I expect** the home controller should not show in the welcome page

## ⚙️ Engineering Details

We want to remove that but actually I have no idea what it can be used for. A short analysis of what the home controller is for would be interesting to add to this ticket.

**Comment by al-niessner** [comment]
It may be possible to remove this but the 30 second google attempt did not provide hope. Unfortunately home controller is the long way to say '/' which then provides the swagger-ui page. It is possible to override the actual behavior of '/' but then swagger-ui will not show up. Hence, removing it may prove to be very difficult. More when I have time.

**Comment by al-niessner** [comment]
Could not remove it, but changed it to be as simple as possible and renamed to "this page : API Documentation". Hope that is sufficient. See attached screenshot for what it looks like now.

![no_more_home_controller](https://user-images.githubusercontent.com/1130658/162794029-d682c405-9f1c-4750-87fe-d5be8e2100f6.png)
