### ISSUE TITLE
Update all endpoints to only allow access to public data.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#113]
## 🐛 Describe the bug

per https://github.com/NASA-PDS/registry-api/issues/106#issuecomment-1081292187, https://github.com/NASA-PDS/registry-api/issues/466 was not sufficiently implemented for all endpoints.

## 📜 To Reproduce
See comment above and https://github.com/NASA-PDS/registry-api/issues/106#issuecomment-1074256749

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @viviant100 FYI, this is a blocker to B12.1 delivery. the requirement here: https://github.com/NASA-PDS/registry-api/issues/466, appears to have not been sufficiently implemented, so table testing for the time being. Also, per the comments above, we should make sure if the I&T team has already tested this, they update their tests to include all endpoints.

**Comment by viviant100** [comment]
@jordanpadams @tloubrieu-jpl  do we have all endpoints documented somewhere?

**Comment by tloubrieu-jpl** [comment]
@viviant100 when deployed the API is self described in the root url.
Of course now non f the services are accessible,  for me at least.

You can try:
https://pds-nasa.gov/api/search/0.4

Or here a screenshot:
![image](https://user-images.githubusercontent.com/60993872/160686220-4252b56e-857a-430a-af27-77d4fef8dc39.png)


It is also documented in the specification of the API, see https://nasa-pds.github.io/pds-api/ (this is being improved), but you can find he details end points there https://nasa-pds.github.io/pds-api/specifications/search-v1.0.0-SNAPSHOT-redoc.html

**Comment by tloubrieu-jpl** [comment]
@viviant100 actually I remember, that the swagger output is not shown in the production deployment because it does not comply with JPL/NASA/PDS styling, but it is available when deployed by default.
