### ISSUE TITLE
Invalid or corrupted registry-api-service.jar file in registry-api-service docker image

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/registry-api#114]
The docker image of the registry-api-service fails to start with the following error.

```
Error: Invalid or corrupt jarfile registry-api-service.jar
```

It was observed that the size of the `registry-api-service.jar` is only 9 bytes in size.

```
root@ef711d416f7e:/usr/local/registry-api-service# ls -l
total 36
-rw-r--r-- 1 root root 10495 Mar 28 18:11 LICENSE.md
-rw-r--r-- 1 root root  1663 Mar 28 18:11 NOTICE.txt
-rw-r--r-- 1 root root  1790 Mar 28 18:11 README.md
-rw-r--r-- 1 root root   798 Mar 29 01:33 application.properties
-rw-r--r-- 1 root root     9 Mar 28 18:12 registry-api-service.jar
-rwxr-xr-x 1 root root  2850 Mar 30 00:17 registry-api-waits-for-elasticsearch.sh
-rw-r--r-- 1 root root    15 Mar 28 18:12 version.txt
root@ef711d416f7e:/usr/local
```

Also, we identified that the following build tries to download the `registry-api-service.jar` file from https://github.com/NASA-PDS/registry-api-service/releases/download/v0.5.0-SNAPSHOT/registry-api-service-0.5.0-SNAPSHOT.jar  and fails due to an unavailable file.

Build logs: https://github.com/NASA-PDS/registry-api/runs/5725273325?check_suite_focus=true#step:6:329

It seems the above build is trying to use the older link https://github.com/NASA-PDS/registry-api-service/releases to download the `registry-api-service.jar`, instead of using the the latest release link at https://github.com/NASA-PDS/registry-api/releases.

It is required to make changes to download the latest version of `registry-api-service.jar`, from the latest release link at https://github.com/NASA-PDS/registry-api/releases.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life @ramesh-maddegoda @jimmie it sounds like this pull request could correct this bug https://github.com/NASA-PDS/registry-api/pull/116

**Comment by nutjob4life** [comment]
That could do it!

**Comment by jimmie** [comment]
Note for 0.5.1 you need to specify two versions as build_args: 'version' (0.5.1) which is the version of the overall release and 'jar_version' (0.5.0-SNAPSHOT) which is the version of the jar file. The latter does default to the former but for 0.5.1 both are necessary.

**Comment by tloubrieu-jpl** [comment]
Sorry @jimmie, @nutjob4life  , this is a mistake in the release process, the jar naming should not be different from the version.  I need to check that

**Comment by nutjob4life** [comment]
Closing this as it was fixed by https://github.com/NASA-PDS/registry-api/pull/120 which has been merged.

Incidentally, the problem was not in my automatic image generation, but in the original `Dockerfile`, which ignored a 404 "Not Found" when retrieving a `.jar` file.
