### ISSUE TITLE
[SECURITY] Upgrade jackson dependencies to remove vulnerability

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#122]
## 💪 Motivation
Vulnerability in jackson dependencies

## 📖 Additional Details

See automated pull request https://github.com/NASA-PDS/registry-api/pull/119 which can not be merged as is.

See other attempt to upgrade on branch 'jackson-upgrade'. This does not work with the integration test and we had no time to solve that before release 12.1

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
closing per #124 for now. will reopen or issue will pop up again in a future scan
