### ISSUE TITLE
As a user I want consistent /type/lidvlid/{child,parent}/{latest,all}

### ISSUE THREAD

**Issue by al-niessner** [NASA-PDS/registry-api#126]
## 💪 Motivation

Current endpoints:

- /bundles/{identifier}/collections
- /bundles/{identifier}/collections/latest
- /bundles/{identifier}/collections/all
- /bundles/{identifier}/products

Why no all and latest for the last endpoint? Collections and products have the same issues.

## ⚖️ Acceptance Criteria

When can change {child,parent} and type elements without breaking. In other words, consistency.

**Comment by tloubrieu-jpl** [comment]
@al-niessner this ticket is in review but I am not sure if it has been implemented and how so. That might be a side effect of the redesign of the end-points. Is it ?

**Comment by al-niessner** [comment]
@tloubrieu-jpl it is part of the redesign

**Comment by tloubrieu-jpl** [comment]
This ticket is a duplicate of https://github.com/NASA-PDS/pds-api/issues/202
