### ISSUE TITLE
[SECURITY] Log4j vulnerability in lexer

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#137]
## Vulnerability
Need to upgrade log4j to log4j2
* https://github.com/NASA-PDS/registry-api/security/dependabot/2
* https://github.com/NASA-PDS/registry-api/security/dependabot/3
* https://github.com/NASA-PDS/registry-api/security/dependabot/6
* https://github.com/NASA-PDS/registry-api/security/dependabot/7

## Software Version
v1.0.0

**Comment by tloubrieu-jpl** [comment]
Complete the fix with commit 52abb18 

Still need to generate a point build with these updates.
