### ISSUE TITLE
Add back the Dockerfile used for the AWS/Fargate deployment

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#140]
This has been removed earlier by @nutjob4life , but this should be made clear (in the README.md) why it is needed and different from the Dockerfile which is now in the repository and used for the continuous deployment in test.

**Comment by jimmie** [comment]
This has been covered by a still as yet pending PR for [registry-api #117](https://github.com/NASA-PDS/registry-api/issues/117)

**Comment by jimmie** [comment]
Closing as fixed by registry-api-117
