### ISSUE TITLE
unexpected behavior with q= query

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#144]
## 🐛 Describe the bug
I had some questions about the API search service:
 
I run this query:
 
[https://pds.nasa.gov/api/search-atm/1.0/products?limit=10&q=(target_name%20eq%20%22Mars%22)](https://urldefense.us/v3/__https:/pds.nasa.gov/api/search-atm/1.0/products?limit=10&q=(target_name*20eq*20*22Mars*22)__;JSUlJQ!!PvBDto6Hs4WbVuu7!cLuBsoFzQjwVd-RL9ckJRuVC60dYqRTlYAexZF_yZBlG-pXynKet1qm2LxlNg_uQ8tcecEFFnA$)
 
but I don't get any results, however, when I run this query:
 
[https://pds.nasa.gov/api/search-atm/1.0/products?limit=10&q=(target_name%20ne%20%22Mars%22)](https://urldefense.us/v3/__https:/pds.nasa.gov/api/search-atm/1.0/products?limit=10&q=(target_name*20ne*20*22Mars*22)__;JSUlJQ!!PvBDto6Hs4WbVuu7!cLuBsoFzQjwVd-RL9ckJRuVC60dYqRTlYAexZF_yZBlG-pXynKet1qm2LxlNg_uQ8tcRNh2iwg$)
 
I do get Mars results.
 
Can you please tell me what I'm doing wrong?

**Comment by tloubrieu-jpl** [comment]
Bug initially reported by Irma Trejo from atmosphere node.

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

From a [change](https://github.com/NASA-PDS/registry-api/commit/900fd0e99a46fab414da25616e3b226aff4bfec9) @jordanpadams  may have approved it seems that eq has change to like.

**Comment by tloubrieu-jpl** [comment]
This ticket is closed as a duplicate of https://github.com/NASA-PDS/registry-api/issues/134
