### ISSUE TITLE
swagger-ui does not show the expected version

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#149]
## 🐛 Describe the bug

The version of the API does not match something I understand in the swagger-ui.html interface. 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/60993872/173312051-d4370a1e-45e8-4159-aa70-af812a2ab070.png">

## 📜 To Reproduce
1. Go to where the registry-api service deployed, for example http://localhost:8081/
2. See the swagger-ui.html page where the request is redirected
3. The version shown in this page is 0.0.1

## 🕵️ Expected behavior

The version should be either the version of the openapi specification in the swagger.yml file or the version of the implementation in the pom.xml file.

## 📚 Version of Software Used
1.1.0-SNAPSHOT
1.0.1

## 🖥 System Info

---

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Which version; ./pom.xml or ./service/pom.xml? I notice they are not the same currently. Should they be the same?

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner,

The current version should be what is in the ./service/pom.xml and they should be the same. Ideally we should not have a specific version in the service/pom.xml but I did not find a way to have it re-use the parent pom version. I should look into that again.

Anyway, for this ticket you can use the version of the service/pom.xml I guess that makes more sense.

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

There are two possible choices for sharing version numbers in a set of maven modules:

1. [settings](https://maven.apache.org/examples/injecting-properties-via-settings.html)
2. [properties](https://sergiuoltean.com/2017/03/27/maven-share-properties-between-modules/)

**Comment by jordanpadams** [comment]
closed per #166
