### ISSUE TITLE
summary-only does not work on products of a collection

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#152]
## 📜 To Reproduce
1. Go to http://pds.nasa.gov/api/search-sbnpsi/1.0/collections/:lidvid/products?summary-only=true
2. See error 500

In addition, the summary.properties field is not populated in the response when the following request is done:

    curl --location --request GET 'http://pds.nasa.gov/api/search-sbnpsi/1.0/collections/urn:nasa:pds:orex.ovirs:data_calibrated/products'

## 🕵️ Expected behavior

There should not be an error but a response containing only the summary of the result.

The list of properties should be filled in the summary object when the request work.

## 📚 Version of Software Used

1.0.0

## 🖥 System Info

---

**Comment by tloubrieu-jpl** [comment]
@gxtchen this should be tested from:

the latest stable version of the registry-api (1.0.2) which can be deployed using the latest stable registry docker compose (1.0.2)
the latest development version should also be tested but the CICD did not work on registry-api

**Comment by jimmie** [comment]
Seems the removal of summary-only in favor of limit=0 has broken this once again.

**Comment by jimmie** [comment]
Note: this bug was applicable to all /class/{id}/class type requests.

PR approved and merged.
