### ISSUE TITLE
apply bug fix on stable release

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#160]
## 💡 Description

Apply the pull request changes from https://github.com/NASA-PDS/registry-api/pull/158 on branch release/1.0.1

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

# DANGER!!

Seems that branch release/1.0.1 no longer exists. Did somebody do a push force?

If you go to #147 then click on the [release/1.0.1](https://github.com/NASA-PDS/registry-api/tree/release/1.0.1) that existed 12 days ago you will get a 404 page.

I have this fix sitting on branch issue_134_r101 (should have named it issue 160 but oh well) to make a PR and merge but do not know which branch to use now that release 1.0.1 is MIA.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner ,

I still have the branch on my local repository. I wil repush it with a .bkp suffix not to override whatever happened to the original branch.

**Comment by tloubrieu-jpl** [comment]
I pushed the branch https://github.com/NASA-PDS/registry-api/tree/release/1.0.1.bkp which should be the same as the original release/1.0.1
