### ISSUE TITLE
implement freetext search

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#17]
@tloubrieu-jpl commented on [Wed Feb 24 2021](https://github.com/NASA-PDS/registry-api-service/issues/5)

Use elasticsearch freetext search as configured in the registry.

Find a way to implement that in the API specification and code it.

**Applicable Requirements**
:unicorn: https://github.com/NASA-PDS/registry-api/issues/460

**Comment by jordanpadams** [comment]
I think is actually completed for what we want here. There should be a new ticket created for a more robust freetext search. See `keyword` query parameter
