### ISSUE TITLE
As a user, I want to be able to paginate over any number of results returned from a query.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#176]
## 💪 Motivation
...so that I can paginate through any number of results returned from the registry, with no performance lag, or restrictions due to tech stack

## 📖 Additional Details

Follow on to NASA-PDS/registry-mgr#53, we need to investigate a better solution for handling pagination. Current solution at NASA-PDS/registry-mgr#54 increased the window limit, which may work for now, but sets an arbitrary top bound and the OpenSearch documentation notes that it could affect performance.

Per discussions on that ticket, the [OpenSearch scroll API](https://opensearch.org/docs/latest/opensearch/rest-api/scroll/) is an option, but would potentially require us to maintain state, which is not RESTful. We need to investigate further to see if there is a solution that can meet both the needs of this requirement while also maintaining the RESTfulness where possible and makes sense

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
This must work especially with the keyword search for the web UI. This is also preventing the notebook to work.

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl @jordanpadams good to close this on the basis of https://github.com/NASA-PDS/registry-api/pull/397, or is the keyword wrinkle keeping it open?  Seems like pagination compatibility should be a concern of #430 rather than this ticket

**Comment by tloubrieu-jpl** [comment]
This ticket can be closed pagination works and integration tests are proving it.
However, the test have been linked to this ticket NASA-PDS/registry-api/352 rather than the current one.
