### ISSUE TITLE
limit=0 is not providing list of properties (fka summary-only)

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api#179]
## 🐛 Describe the bug
summary-only was replaced in favor of limit=0 - which should provide only a list of properties, no actual product information. Specifying either on current HEAD is not providing expected results:

limit=0
{
  "summary" : {
    "q" : "",
    "hits" : 10000,
    "took" : 80,
    "start" : 0,
    "limit" : 0,
    "sort" : [ ],
    "properties" : [ ]
  }
}

summary-only=true
(summarily ignored and returns product information, which is expected)

## 📜 To Reproduce
1. specify "limit=0" to any API endpoint that returns a list (e.g. /products?limit=0)
2. Observe results shown above.3. 

## 🕵️ Expected behavior
Something similar to the following should be returned:
{
  "summary" : {
    "q" : "",
    "hits" : 10000,
    "took" : 473,
    "start" : 0,
    "limit" : 100,
    "sort" : [ ],
    "properties" : [ "_package_id", "description", "disp:Display_Direction.disp:horizontal_display_axis", "disp:Display_Direction.disp:horizontal_display_direction", "disp:Display_Direction.disp:vertical_display_axis", "disp:Display_Direction.disp:vertical_display_direction", "geom:Display_Direction.geom:horizontal_display_axis", "geom:Display_Direction.geom:horizontal_display_direction", "geom:Display_Direction.geom:vertical_display_axis", "geom:Display_Direction.geom:vertical_display_direction", "geom:Object_Orientation_RA_Dec.geom:celestial_north_clock_angle", "geom:Object_Orientation_RA_Dec.geom:declination_angle", "geom:Object_Orientation_RA_Dec.geom:right_ascension_angle", "geom:Reference_Frame_Identification.geom:name", "img:Exposure_Parameters.img:exposure_duration", "img:Filter.img:center_filter_wavelength", "img:Filter.img:filter_name", "lid", "lidvid", "ops:Data_File_Info.ops:creation_date_time", "ops:Data_File_Info.ops:file_name", "ops:Data_File_Info.ops:file_ref", "ops:Data_File_Info.ops:file_size", "ops:Data_File_Info.ops:md5_checksum", "ops:Data_File_Info.ops:mime_type", "ops:Harvest_Info.ops:harvest_date_time", "ops:Harvest_Info.ops:node_name", "ops:Label_File_Info.ops:creation_date_time", "ops:Label_File_Info.ops:file_name", "ops:Label_File_Info.ops:file_ref", "ops:Label_File_Info.ops:file_size", "ops:Label_File_Info.ops:md5_checksum", "ops:Tracking_Meta.ops:archive_status", "pds:Array_2D_Image.pds:axes", "pds:Array_2D_Image.pds:axis_index_order", "pds:Array_2D_Image.pds:local_identifier", "pds:Array_2D_Image.pds:offset", "pds:Axis_Array.pds:axis_name", "pds:Axis_Array.pds:elements", "pds:Axis_Array.pds:sequence_number", "pds:Citation_Information.pds:description", "pds:Citation_Information.pds:editor_list", "pds:Citation_Information.pds:publication_year", "pds:Element_Array.pds:data_type", "pds:File.pds:file_name", "pds:Header.pds:object_length", "pds:Header.pds:offset", "pds:Header.pds:parsing_standard_id", "pds:Identification_Area.pds:information_model_version", "pds:Identification_Area.pds:logical_identifier", "pds:Identification_Area.pds:product_class", "pds:Identification_Area.pds:title", "pds:Identification_Area.pds:version_id", "pds:Internal_Reference.pds:lid_reference", "pds:Internal_Reference.pds:reference_type", "pds:Investigation_Area.pds:name", "pds:Investigation_Area.pds:type", "pds:Local_Internal_Reference.pds:local_identifier_reference", "pds:Local_Internal_Reference.pds:local_reference_type", "pds:Modification_Detail.pds:description", "pds:Modification_Detail.pds:modification_date", "pds:Modification_Detail.pds:version_id", "pds:Object_Statistics.pds:maximum_scaled_value", "pds:Object_Statistics.pds:minimum_scaled_value", "pds:Observing_System_Component.pds:name", "pds:Observing_System_Component.pds:type", "pds:Primary_Result_Summary.pds:processing_level", "pds:Primary_Result_Summary.pds:purpose", "pds:Science_Facets.pds:discipline_name", "pds:Science_Facets.pds:facet1", "pds:Science_Facets.pds:wavelength_range", "pds:Target_Identification.pds:name", "pds:Target_Identification.pds:type", "pds:Time_Coordinates.pds:start_date_time", "pds:Time_Coordinates.pds:stop_date_time", "product_class", "ref_lid_facility", "ref_lid_instrument", "ref_lid_investigation", "ref_lid_target", "ref_lid_telescope", "title", "vid" ]
  }
}

**Comment by jordanpadams** [comment]
Per offline discussion, planning to revert the changes associated with https://github.com/NASA-PDS/pds-api/issues/173, and keep summary-only for the time being, and revisit that ticket in the future.

@jimmie FYI

**Comment by jimmie** [comment]
Solution determined which preserved the limit=0 behavior.

PR approved and merged.
