### ISSUE TITLE
/all suffix returns a message which I don't understand

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#190]
## 🐛 Describe the bug

With the request:
http://localhost:8080/collections/urn%3Anasa%3Apds%3Ainsight_rad%3Adata_derived%3A%3A7.0/all

The returned message is:
The lidvid urn:nasa:pds:insight_rad:data_derived::7.0 was of type Product_Collection not of type bundles

## 📜 To Reproduce
1. Use the integration test deployed with docker compose, see https://github.com/NASA-PDS/registry/tree/main/docker
2. Start the service with profile `int-registry-batch-loader`
3. Make the request in a browser `http://localhost:8080/collections/urn%3Anasa%3Apds%3Ainsight_rad%3Adata_derived%3A%3A7.0/all`
5. Note that the same request without the /all suffix works

## 🕵️ Expected behavior

The request should return all the versions available for lid `urn:nasa:pds:insight_rad:data_derived`

## 🖥 System Info

---

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

cut-n-paste error in the deprecated interface.

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4212026
