### ISSUE TITLE
version number are treated as floats

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#191]
## 🐛 Describe the bug

version in the result shows as 7 for example instead of 7.0

The content of opensearch sounds ok, see:
https://localhost:9200/registry/_search

## 📜 To Reproduce
1. Use the integration test deployed with docker compose, see https://github.com/NASA-PDS/registry/tree/main/docker
2. Start the service with profile int-registry-batch-loader
3. Make request in a terminal:
`curl --get 'http://localhost:8080/collections/urn%3Anasa%3Apds%3Ainsight_rad%3Adata_derived%3A%3A7.0' --header 'Accept:application/vnd.nasa.pds.pds4+json'`
5. The version attributes in the response are 7 instead of 7.0

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
@tloubrieu-jpl not sure if this is something that has been fixed per something @al-niessner has done? Or if there is something else we need to do?

I seem to remember during conversation about implementing "latest" versus "all" that we would need a separate `version_number` (or `version_major`/`version_minor`) field to track the actual numeric comparison of versions, versus the PDS4 IM version field that is a string.

**Comment by tloubrieu-jpl** [comment]
It does not sound like it is a type issue in the OpenSearch database itself, so I don't know if that would help to sort the versions by latest (and I don't believe that would be a good solution anyway for that). We can discuss that at a breakout.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

The PDS4 transformation treats the vid as a float. I do not know if this an XML inherited thing or not. JSON, when representing 7.0 knows that 7 is equivalent in numeric terms. What the translator does not understand is that vid is int.int which, despite its similar look, is not a float nor a number of any kind.

**Comment by alexdunnjpl** [comment]
Asking the dumb question, don't shoot me - are you referring to the root-level `_version` attribute, or stuff like 

 - `pds:Modification_Detail/pds:version_id`
 - `pds:Identification_Area/pds:version_id`
 - `vid`
 ?
 
 The former is the ES/OS document revision id, and the latter three are showing correctly in my local registry instance (albeit for a different bundle) using an equivalent `curl` call

**Comment by alexdunnjpl** [comment]
Currently unable to replicate this behaviour - the product in question is not returned by the API following deployment of a fresh instance of `int-registry-batch-loader` docker compose

**Comment by alexdunnjpl** [comment]
When requested response type is `application/vnd.nasa.pds.pds4+json` rather than `application/json`, relevant data is loaded from one of the blobs, not the (correct, string-valued) corresponding attributes visible in the OS doc.

Confirmed that the source data in the blob itself is the issue

```json
{
  "Product_Collection": {
    "Identification_Area": {
      "product_class": "Product_Collection",
      "Modification_History": {
        "Modification_Detail": [
          {
            "modification_date": "2018-02-14",
            "description": "Delivery test version",
            "version_id": 0.9
          },
          {
            "modification_date": "2019-06-26",
            "description": "This collection contains InSight Release 1, part 2, derived data.\r\n                    See Release Notes document in the Reference List for details.",
            "version_id": 1
          },
          {
            "modification_date": "2019-09-23",
            "description": "This collection is updated for InSight Release 2.\r\n                    See Release Notes document in the Reference List for details.",
            "version_id": 2
          },
          {
            "modification_date": "2019-12-11",
            "description": "This collection is updated for InSight Release 3.\r\n                    See Release Notes document in the Reference List for details.",
            "version_id": 3
          },
          {
            "modification_date": "2020-03-09",
            "description": "This collection is updated for InSight Release 4.\r\n                    See Release Notes document in the Reference List for details.",
            "version_id": 4
          },
          {
            "modification_date": "2020-06-02",
            "description": "This collection is updated for InSight Release 5.\r\n                    See Release Notes document in the Reference List for details.",
            "version_id": 5
          },
          {
            "modification_date": "2020-09-09",
            "description": "This collection is updated for InSight Release 6.\r\n                    See Release Notes document in the Reference List for details.",
            "version_id": 6
          },
          {
            "modification_date": "2020-12-10",
            "description": "This collection is updated for InSight Release 7.\r\n                    See Release Notes document in the Reference List for details.",
            "version_id": 7
          }
        ]
      },
      "information_model_version": "1.10.1.0",
      "logical_identifier": "urn:nasa:pds:insight_rad:data_derived",
      "version_id": 7,
      "Citation_Information": {
        "publication_year": 2018,
        "description": "InSight RAD Derived Data Collection"
      },
      "title": "InSight RAD Derived Data Collection"
    },
    <<<irrelevant data snipped>>>
  }
}
```

Adding some notes for when I loop back to it later this week

 - decoding the blob is best performed by dropping a breakpoint in the API PDS4ProductFactory L89
 - after a bit of searching, it's not clear where the blob comes from or how it's generated in the first place.  It's not in the source xml, but a global search/replace for "blob" in `harvest` yields nothing

**Comment by tloubrieu-jpl** [comment]
Thanks @alexdunnjpl , next step is to look at `harvest` and see if this behavior can be improved.

**Comment by alexdunnjpl** [comment]
Issue is specific to `application/vnd.nasa.pds.pds4+json` and does not appear in default response or with `Accept:application/json` - need to re-confirm that this is because that's the only format that looks at the blob content (probably, but it's been a while)

**Comment by alexdunnjpl** [comment]
[Error occurs when writing JSONObject to String, here](https://github.com/NASA-PDS/registry-common/blob/c03d2932618b454a6c4f8197ef1a386378f8868c/src/main/java/gov/nasa/pds/registry/common/meta/FileMetadataExtractor.java#L244)

N.B. values extracted from XML are "correctly"-typed as decimal but the root(ish) cause is that they should be extracted as Strings.

![image](https://user-images.githubusercontent.com/75815303/225426868-089050ea-f94e-4719-a756-9f37d3c391e2.png)

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl  there are a couple of possible solutions I can see:

 - [change the XML parser configuration ](https://stleary.github.io/JSON-java/index.html) to use `withKeepStrings(true)`. This will have the effect of making *all* fields stored in JSON blobs string-typed.  This may break something if consumers of our API aren't doing their own type-checking and are relying on floating-point and integer values being represented as JSON int/float types.
 - use XML types to differentiate version id fields from other float-like fields, and only keep those as strings (obviously unworkable to introduce a new requirement into the label ecosystem, but figured I'd mention it)
 - manually convert affected values, using XML paths to target them.  I'll need to know whether it's just a static `Product_{Type}/Identification_Area/Modification_history/Modification_Detail[{idx}]/version_id` across the board, or potentially more complicated than that.

Whatever decision we go with, it's a change to `registry-common` so may affect more than just the API (probably not, but maybe)

Once resolved and released, it'll be necessary to re-harvest everything to see the fix.

**Comment by jordanpadams** [comment]
@alexdunnjpl 

> manually convert affected values, using XML paths to target them. I'll need to know whether it's just a static Product_{Type}/Identification_Area/Modification_history/Modification_Detail[{idx}]/version_id across the board, or potentially more complicated than that.

so you are saying we would need to script a reindex of this field in the registry with the version_id field defined as a string?

**Comment by jordanpadams** [comment]
I think this is really our best solution. I don't think option 1 will work because the switch in JSON type seems like it will be a bit kludgy from a user perspective.

**Comment by tloubrieu-jpl** [comment]
Thanks @alexdunnjpl @jordanpadams , the option 3, have a list of number typed Xpath is ok to me. But I was thinking that would run in harvest, since harvest is converting to JSON, we can introduce the different between string and number there.

But we will still have the issue of converting/re-indexing the pre-loaded document in the registry, for which we would then need a specific script. Used only once.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl agree I think this update is needed in multiple places.

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl I don't know whether a re-index is actually required (though again, it *will* be necessary to reingest all data to end up with products' documents containining JSON blobs containing the correct values, so that's not really any better), because VIDs look like they're index-typed as keywords (and presumably would remain so)

```
parallels@parallels-Parallels-Virtual-Platform:~$ curl -k -u admin:admin https://localhost:9200/registry | json_pp | grep -A 1 version
            "insight:Observation_Information/insight:software_version_id" : {
               "type" : "keyword"
--
            "pds:Identification_Area/pds:information_model_version" : {
               "type" : "keyword"
--
            "pds:Identification_Area/pds:version_id" : {
               "type" : "keyword"
--
            "pds:Modification_Detail/pds:version_id" : {
               "type" : "keyword"

``` 

This is also confused a bit by the fact that the values which are in the documents themselves are correct, 

```
parallels@parallels-Parallels-Virtual-Platform:~$ curl -k -u admin:admin https://localhost:9200/registry/_search | json_pp | grep -A 1 'pds:Modification_Detail/pds:version_id'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  126k  100  126k    0     0  4624k      0 --:--:-- --:--:-- --:--:-- 4698k
               "pds:Modification_Detail/pds:version_id" : [
                  "0.1",
--
               "pds:Modification_Detail/pds:version_id" : [
                  "0.9",
--
               "pds:Modification_Detail/pds:version_id" : [
                  "0.9",
--
               "pds:Modification_Detail/pds:version_id" : [
                  "1.0",
--
               "pds:Modification_Detail/pds:version_id" : [
                  "1.0"
--
               "pds:Modification_Detail/pds:version_id" : [
                  "1.0"
--
```

So the scope of what we're fixing is 
 - the JSON blob copy of the label
 - the versions served by the API **only when passed** `Accept:application/vnd.nasa.pds.pds4+json`, because it uses the JSON blob (not the OS-indexed metadata) to populate its responses in that case 
 - anything else that uses that JSON blob (mentioned here as CYA)

@tloubrieu-jpl the conversion is happening in harvest('s execution), but the conversion itself is a call to a `registry-common` utility for extracting file metadata ([see link in this comment](https://github.com/NASA-PDS/registry-api/issues/191#issuecomment-1470750070))

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl , 
- we use [change the XML parser configuration ](https://stleary.github.io/JSON-java/index.html)to use withKeepStrings(true).

For now we accept that some numbers will be presented as string in the JSON blob.

**Comment by alexdunnjpl** [comment]
Will be resolved by https://github.com/NASA-PDS/registry-common/pull/33
