### ISSUE TITLE
CICD did not publish the jar on artifactory

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#2]
See action for stable release: https://github.com/NASA-PDS/pds-api-javalib/actions/runs/1575376976

The jar is not seen on the artifactory.

**Comment by tloubrieu-jpl** [comment]
transfered from obsolete pds-api-javalib repository

**Comment by jordanpadams** [comment]
closed per https://search.maven.org/artifact/gov.nasa.pds/api . this will hopefully also work with new repo
