### ISSUE TITLE
observational end-point returns collections

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#202]
## 🐛 Describe the bug

The following request:

`curl --request GET 'http://localhost:8081/classes/observationals?limit=10'`

Returns collections instead of observational products

**Comment by gxtchen** [comment]
@tloubrieu-jpl Can I test this with registry docker? What version can I test this with?

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4212028
