### ISSUE TITLE
As a registry-tool/registry-user I want to ensure leading multiple forward-slashes in request paths are stripped out

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api#208]
## 🧑‍🔬 User Persona(s)
Some tools insert and extra forward slash between base registry URL (pds.nasa.gov/api/search/<version>) and the command path (/bundles/<lidvid>). 

## 💪 Motivation
This causes a 503 from the service which does not recognize the request which arrives w/ these multiple slashes (//bundles/<lidvid>) but should be tolerated.

## 📖 Additional Details
This can be handled at the Cloudfront layer

## ⚖️ Acceptance Criteria
**Given** a registry request URL; https://pds.nasa.gov/api/search/1.0/bundles/urn:nasa:pds:duxbury_pdart14_mariner69::2.0
**When** I submit this URL either in a browser or via curl
**Then I expect** the request to return a 200 and valid results, not a 503 response

## ⚙️ Engineering Details
Have the cloudfront function detect if multiple leading slashes exist and replace them with one.

**Comment by jimmie** [comment]
PR 209 reviewed and merged.

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4133328
