### ISSUE TITLE
swaggger ui error in production

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#211]
## 🐛 Describe the bug

See URL https://pds.nasa.gov/api/search/1/swagger-ui/index.html

## 🕵️ Expected behavior

The  description of the API end-point should be visible when one arrives on the page.

## 📚 Version of Software Used

registry-api 1.1.11 in the production environment

## 🩺 Test Data / Additional context

The behavior is different in production since the base URL of the API service is not a host name (as for `http://pds.nasa.gov` or `http://localhost:8080`) but there is a piece of URL path (`/api/search/1`) before the API sub-path. The swagger ui works if you replace `/apidocs` by `https://pds.nasa.gov/api/search/1/api-docs` in the input text on the top.

We need that to work by default

##  🏞Screenshots

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/60993872/207650054-9f360d8a-9eb3-4e55-90e6-978e10713789.png">

## 🖥 System Info

---

**Comment by tloubrieu-jpl** [comment]
Some updates have been done in branch `springdoc` since the solution to have a working swagger-ui behing a reverse proxy was not possible with current library (springfox).

To make that fully work, I am also starting to upgrade the openapi generator maven plugin to the community version which will make us consistent with the python api client and apparently the project is the most dynamic to have the latest features and bug fixes.

**Comment by gxtchen** [comment]
@tloubrieu-jpl production server is still showing the same error.

**Comment by tloubrieu-jpl** [comment]
@gxtchen the version 1.2.0 tested by I&T is not deployed in production yet. I will deploy on gamma today where you should be able to test, as if in production.

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen ,

I deployed on gamma https://pds.nasa.gov/api/search-en-gamma/1/swagger-ui/index.html
And I tested at the same time, it still fails, so I created this ticket https://github.com/NASA-PDS/registry/issues/191

You can add it to the test results.
