### ISSUE TITLE
As a user, I want the API to support redundant `/` in the url

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#212]
## 🧑‍🔬 User Persona(s)

API user

## 💪 Motivation
...so that I don't need to pay attention to the root URL being defined as `https://pds.nasa.gov/search/api/1/` (with trailing /) or `https://pds.nasa.gov/search/api/1` (without trailing '/')

## ⚖️ Acceptance Criteria
**Given** a deployed API server
**When I perform** request http://{hostname}/api_root_url//api_query_subpath
**Then I expect** the same result as for http://{hostname}/api_root_url/api_query_subpath (without double `/`)

## ⚙️ Engineering Details

See configuration of spring-boot https://spring.io/blog/2020/06/30/url-matching-with-pathpattern-in-spring-mvc

**Comment by tloubrieu-jpl** [comment]
It worsks in the API though the default spring-boot pattern used to decode the URL path

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4133327
