### ISSUE TITLE
migrate  to jdk 17

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#218]
## 💡 Description

We need to upgrade to this jdk LTS version.
That will allow us to merge this pull request https://github.com/NASA-PDS/registry-api/pull/201

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl is this a change to the codebase (make compatible with JDK17 if not already), or to the deployments (in this case I guess the docker image used by `registry`?

**Comment by jordanpadams** [comment]
@alexdunnjpl this is for the codebase. it is my understanding from @tloubrieu-jpl before he left that the current registry-api does not work with jdk17

**Comment by jordanpadams** [comment]
Status: going to take a bit to dig here.
