### ISSUE TITLE
Establish parity between application.properties and application.properties.aws files

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api#220]
## 💡 Description
Certain configuration parameters (e.g. server.forward-headers-strategy, filter.archiveStatus, etc.) have been added/changes in the application.properties file. These changes need to be reflected in the application.properties.aws file as well such that cloud deployments reflect the same behavior.

Note: 
```
# use only for development purpose, left it to true otherwise
openSearch.sslCertificateCNVerification=true
```
will not be added since it appears the default is desired and we do not want to introduce unintended behavior by adding this parameter (a bit twitchy about this parameter since it involves certs).

**Comment by jimmie** [comment]
Will also move some config parameters around in application.properties.aws to agree w/ their locations in application.properties, making it easier to compare.

**Comment by jimmie** [comment]
Note that this file (along with the registry-api jar file) is read in at the time the docker image is built so a new build of the registry-api artifacts is not necessary to support these changes.

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/registry-api/pull/221
