### ISSUE TITLE
As a user, I want to know the members of a bundle product

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#223]
## 🧑‍🔬 User Persona(s)

Data User

## 💪 Motivation
...so that I can get the collections of a bundle (formerly `bundles/{lidvid}/collections`

## 📖 Additional Details

~looks like the following were implemented:~
```
products/{identifier}/member-of
products/{identifier}/member-of/member-of
```
~but we are missing:~
```
products/{identifier}/members
products/{identifier}/members/members
```

## ⚖️ Acceptance Criteria
~**Given** a bundle lidvid
**When I perform** `curl --get `https://api.url.com/products/{identifier}/members`
**Then I expect** the get the collections associated with that bundle~

~**Given** a bundle lidvid
**When I perform** `curl --get `https://api.url.com/products/{identifier}/members/members`
**Then I expect** the get all products from all collections that belong to this bundle~

**Given** a bundle lidvid
**When I perform** `curl --get `https://api.url.com/classes/bundles/{identifier}/members/members`
**Then I expect** the get all products from all collections that belong to this bundle

**Given** a bundle lidvid
**When I perform** `curl --get `https://api.url.com/classes/bundles/{identifier}/members`
**Then I expect** the get the collections associated with that bundle

**Comment by alexdunnjpl** [comment]
@jordanpadams is it too late for discussion about the design of these endpoints?

To my mind, it seems clearer to have
../bundles/{id}/collections (returns all collections in bundle)
../bundles/{id}/{products | members} (returns all products, including collections, in bundle)
../bundles/{id}/dataproducts* (returns all non-collection products in bundle)

\* I still haven't worked out what the term for "non-container" products is, but there has to be one

Then in the other direction (possibly this is a terrible idea - and I'm not sure why we even need it given that I imagine a product's metadata should include the id of its collection and bundle, if applicable - but brainstorming)

../products/{id}/bundle (returns redirect to correct ../bundles/{id} or ../products/{id} for enclosing bundle)
../products/{id}/collection (returns redirect to correct ../collections/{id} or ../products/{id} for enclosing collection)

**Comment by jordanpadams** [comment]
@alexdunnjpl unfortunately that design ship has definitely sailed. we have flip-flopped back and forth in the design numerous times.

for now we are just going to support both sets of endpoints for the foreseeable future.

**Comment by alexdunnjpl** [comment]
@jordanpadams given [@tloubrieu-jpl 's comment](https://github.com/NASA-PDS/registry-api/issues/222#issuecomment-1367774017)

> the /members or member-of URL only applies to the new endpoints /classes/{class}, we don’t need to implement that on old endpoints eg /collections/{Id}/members is not a valid endpoint and should return 404. The old endpoint is /collections/{Id}/products . That should not work either on /products/{id}/members which should return 404. But /products/{id}/collections or /products/{id}/bundles should work as for the deprecated endpoints scheme.

is there any action to be taken here?

**Comment by jordanpadams** [comment]
@alexdunnjpl agreed on:

> we don’t need to implement that on old endpoints eg /collections/{Id}/members 

but I believe we still need:

```
/products/{id}/members
/products/{id}/members/members
```

as noted, we can do this using something like:
```
/classes/bundles/members
/classes/bundles/members/members
```

but since we have the `member-of` endpoints implemented (⬆️ the aggregation tree), it just seems to make sense to me that we have the other route (⬇️ the aggregation tree). giving us:

```
/products/{id}/members
/products/{id}/members/members
/products/{id}/member-of
/products/{id}/member-of/member-of
```

in other words, I think this requirement is actually partially implemented because you can use the `/classes/bundles/members/members` endpoint, but this will make it fully implemented depending upon how the user is approaching the data.

**Comment by jordanpadams** [comment]
@alexdunnjpl the other option is we remove:

```
/products/{id}/member-of
/products/{id}/member-of/member-of
```

But I imagine adding the endpoints is almost the same amount of work. I think the update requires:

1. update to swagger API: https://app.swaggerhub.com/apis/PDS_APIs/registry/main
2. add the controller functionality

@al-niessner can probably provide some guidance here as well

**Comment by alexdunnjpl** [comment]
It's your call (or Thomas'? I'm not actually clear) but given that 
 - `/products` returns a heterogeneous collection of basic and aggregate products (where the members/member-of subpaths are "bad" ops)
 - identical functionality is provided by the class-specific endpoints*, in a way that makes sense
 - it seems like any context from which a consumer would want to call the members/member-of's would know which class of product they're querying, and would thus know prima facie which class-specific endpoint to call
 
 I'd suggest that the existence of the `/products/{id}/*` endpoints are needless and somewhat confusing (the API should communicate the nature of the underlying data where possible, imho) and it would be best to remove the swagger listings for these currently-busted endpoints, rather than implementing/fixing them.
 
 *the wrinkle in this is that there's still some inconsistency due to the fact that the `member-of` subpaths are defined for `/products/{id}/...` even though it's a "bad" op for bundles.

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl , @jordanpadams 

That would be useful to have @al-niessner opinion on that.

From my point of view we already have:
`{{baseUrl}}/classes/bundles/:lidvid/members`
and
`{{baseUrl}}/classes/bundles/:lidvid/members/members`

which work and answer the requirement of this ticket.

If we want to implement that on the generic end-point `/product/:lidvid/members` we will have to manage different cases depending of the class of the lidvid. That is not as simple. Do we really need that ?

**Comment by al-niessner** [comment]
@alexdunnjpl @jordanpadams @tloubrieu-jpl 

No opinion on endpoints.

**Comment by alexdunnjpl** [comment]
Two votes for removing them from swagger and one abstain but this isn't necessarily a democracy... @jordanpadams ?

**Comment by jordanpadams** [comment]
@alexdunnjpl @tloubrieu-jpl let's just cancel this for now and wait to see if anyone complains. it seems a bit a counterintuitive having the `member-of` endpoints implemented and not the `members`, but I see the reason for that.
