### ISSUE TITLE
Keyword search does not work on registry-api deployed on pds.nasa.gov

### ISSUE THREAD

**Issue by jjacob7734** [NASA-PDS/registry-api#227]
## 🐛 Describe the bug
The result from a search query to https://pds.nasa.gov/api/search/1/ does not change if the `keyword` modifier is used.  The documentation at https://nasa-pds.github.io/pds-api/guides/search/endpoints.html indicates  that `keyword` is a valid parameter.  The example given is `keyword=insight`. 

## 📜 To Reproduce
1. Run this search with no keyword specification: `curl --get 'https://pds.nasa.gov/api/search/1/products' --header 'Accept: application/json' | json_pp > out_nokeyword.json`
2. Run this search with `keyword=insight` specified:  `curl --get 'https://pds.nasa.gov/api/search/1/products?keyword=insight' --header 'Accept: application/json' | json_pp > out_keyword_insight.json`
3. Compare `out_nokeyword.json` and `out_keyword_insight.json` to see that they are the same.

## 🕵️ Expected behavior

I expected the `keyword=insight` modifier to limit the result to only those products that match the `insight` keyword.

## 📚 Version of Software Used

This uses the search API deployed at https://pds.nasa.gov/api/search/1/. 

## 🖥 System Info
 - OS: macOS 12.6.1 (Monterey)
 - Curl Version:  curl 7.80.0 (x86_64-apple-darwin13.4.0) libcurl/7.80.0 OpenSSL/1.1.1m zlib/1.2.11 libssh2/1.9.0 nghttp2/1.46.0

---

**Comment by jordanpadams** [comment]
@jimmie can you confirm you are seeing this same issue on a local deployment?

**Comment by tloubrieu-jpl** [comment]
This break requirement https://github.com/NASA-PDS/registry-api/issues/460

**Comment by jimmie** [comment]
yes, I am seeing this on a local deployment of the registry service from the latest code on the main branch, running against the production EN Opensearch.

**Comment by tloubrieu-jpl** [comment]
Hi @jjacob7734 , @jimmie , actually the bug is in the documentation where `keyword` should be with an 's'. I updated the doc, see https://nasa-pds.github.io/pds-api/guides/search/endpoints.html

Upgrade is done in commit c3fe6f21da8ea87fe58b6dcf9f250d34aa85db43

**Comment by jjacob7734** [comment]
Thanks, @tloubrieu-jpl.  There's one more small update needed in the documentation at https://nasa-pds.github.io/pds-api/guides/search/endpoints.html.  I see you updated to `keywords` in the `Query Parameter` column, but that update is also needed in the `Example` column in that table.  That's great that this was the issue though.  I confirmed using `keywords` with an `s` returns good matches.
