### ISSUE TITLE
api not returning information on yesterday's upload (and status changed to archived) to the registry

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/registry-api#230]
## 🐛 Describe the bug

Yesterday the epoxi_mri::1.0 dataset information was loaded to the registry and 
the status was changed to archived (yay!).  An Open Search confirmed the 
ops:Tracking_Meta/ops:archive_status for the bundle members to be "archived".
When the api request was made, 'Not found' (api Version 1.1) and "Internal Server 
Error" (api version 1.0) errors were returned.  It has been over 15 hours and those
continue to be the responses.

## 📜 To Reproduce

1. For Version 1.0 (which worked in the September-October 2022 time frame), type 

   curl https://pds.nasa.gov/api/search-sbnumd/1.0/bundles/urn:nasa:pds:epoxi_mri | json_pp

2. See error3. 

3. For Version 1.1, type 4. 

    curl -get 'https://pds.nasa.gov/api/search/1.1/classes/bundles/urn:nasa:pds:epoxi_mri::1.0/members' --header 'Accept: application/json'

 
## 🕵️ Expected behavior

I expect the registry information to be displayed.
  
## 📚 Version of Software Used

Both 1.0 and 1.1 were tried.

##  🏞Screenshots

For Version 1.0

curl https://pds.nasa.gov/api/search-sbnumd/1.0/bundles/urn:nasa:pds:epoxi_mri | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   113    0   113    0     0    144      0 --:--:-- --:--:-- --:--:--   143
{
   "status" : 500,
   "path" : "/bundles/urn:nasa:pds:epoxi_mri",
   "timestamp" : 1670936890223,
   "error" : "Internal Server Error"

For Version 1.1

curl -get 'https://pds.nasa.gov/api/search/1.1/classes/bundles/urn:nasa:pds:epoxi_mri::1.0/members' --header 'Accept: application/json'
{"timestamp":1670935528268,"status":500,"error":"Internal Server Error","path":"/classes/bundles/urn:nasa:pds:epoxi_mri::1.0/members"}

## 🖥 System Info
    Linux
    n/a
    n/a

---

**Comment by jordanpadams** [comment]
@tloubrieu-jpl just wanted to confirm if this is fixed with the current to-be-tagged point build?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @plawton-umd I am looking at that now, sorry I missed it earlier

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @plawton-umd this bug is a duplicate of https://github.com/NASA-PDS/registry-api/issues/213

This occurs because the bundle is missing properties (here `pds:Time_Coordinates/pds:start_date_time`). 

I don't know yet if this is a regression in our API server code. But we will fix that to support PDS4 products with 'less' metadata. Sorry for the inconvenience.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl it may actually be we have not come across data sets missing that metadata.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl is there some other ticket we need to address here? or will this be fixed with an upgraded deployment of the API?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams there is no way to be sure but the error @plawton-umd has experience happened after the v1.1.11 of registry-api was deployed with this know bug.
The stable release (1.1.12) fixing this bug is now ready but I will not be able to deploy in production without Jimmie. I am trying now to deploy it on gamma but I might not be able to make itbefore I go on vacation at the end of today.

**Comment by plawton-umd** [comment]
@jordanpadams @tloubrieu-jpl 

Via OpenSearch confirmed entries are status archived.  Then tried api.  
All the api variations I tried based on https://nasa-pds.github.io/pds-api/guides/search/endpoints.html
and the 2022-Dec-23 email from @jimmie failed in similar manner as the examples below

curl -get 'https://pds.nasa.gov/api/search-sbnumd/1/products/urn:nasa:pds:epoxi_mri' --header 'Accept: application/json'
{"timestamp":1672873416981,"status":500,"error":"Internal Server Error","path":"/products/urn:nasa:pds:epoxi_mri"}

curl -get 'https://pds.nasa.gov/api/search/1/products/urn:nasa:pds:epoxi_mri' --header 'Accept: application/json'
{"timestamp":1672873446581,"status":500,"error":"Internal Server Error","path":"/products/urn:nasa:pds:epoxi_mri"}

curl -get 'https://pds.nasa.gov/api/search/1/products/urn:nasa:pds:epoxi_mri::1.0' --header 'Accept: application/json'
{"timestamp":1672873489046,"status":500,"error":"Internal Server Error","path":"/products/urn:nasa:pds:epoxi_mri::1.0"}

curl -get 'https://pds.nasa.gov/api/search/1.1/products/urn:nasa:pds:epoxi_mri::1.0' --header 'Accept: application/json'
{"timestamp":1672873942650,"status":500,"error":"Internal Server Error","path":"/products/urn:nasa:pds:epoxi_mri::1.0"}

**Comment by jordanpadams** [comment]
@plawton-umd apologies for the errors. we are having some issues rolling out a new deployment of the Registry + API, and the holidays threw a wrench into that as well. we will hopefully have this resolved ASAP and let you know.

**Comment by tloubrieu-jpl** [comment]
@plawton-umd this bug is fixed with version 1.1.12 deployed in production.
