### ISSUE TITLE
Move scheduled execution of provenance.py to an AWS-based solution

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api#232]
## 💡 Description
The provenance.py script will soon be deployed on pdscloud-prod1 in pds4's crontab. We should consider employing this script in an AWS-based manner, such as AWS Batch.

This also provides the means by which we can use something like Secrets Manager to maintain the Opensearch credentials.

**Comment by jimmie** [comment]
After discussions during the SA office hour, we propose the approach of AWS EventBridge Scheduler (obviously for scheduling) driving the invocation of the provenance as an ECS (Fargate) standalone task. Credentials will be injected into the ECS container as environment variables and other runtime parameters from the Parameter Store.

Greatest amount of work is to create the container image that runs the script.

**Comment by jimmie** [comment]
Solution design is documented here: https://wiki.jpl.nasa.gov/pages/viewpage.action?spaceKey=PDSEN&title=Registry+Provenance+Execution

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/registry-api/pull/253
