### ISSUE TITLE
requests with bad `q=` syntax should return 400 error

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#241]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did request:

curl --request GET 'http://localhost:8080/classes/observationals?limit=10&q=weefwe'    

I sm getting a 500 error     
{"timestamp":1675125550678,"status":500,"error":"Internal Server Error","path":"/classes/observationals"}% 

### 🕵️ Expected behavior

I expected to get a 40 error saying bad q syntax, possibly with a link to the documentation on https://nasa-pds.github.io/pds-api/guides/search/endpoints.html#query-string-syntax

### 📜 To Reproduce

```bash
1. curl --request GET 'http://localhost:8080/classes/observationals?limit=10&q=weefwe'    
2. Note 500 error
```

### 🖥 Environment Info
All OSes apply

### 📚 Version of Software Used

latest version

### 🩺 Test Data / Additional context

N/A

### 🦄 Related requirements

Numerous

### ⚙️ Engineering Details

N/A

**Comment by jordanpadams** [comment]
@tloubrieu-jpl ideally I feel like we should be able to support this since OpenSearch can, but I get that our custom lexer makes this a little more difficult.

we should be sure to note in the error that the `keywords` parameter may be more applicable.

**Comment by tloubrieu-jpl** [comment]
This is closed by PR https://github.com/NASA-PDS/registry-api/pull/266
