### ISSUE TITLE
 /classes/collections/<lidvid>/members does not return data when it should

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-api#247]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

The endpoints /classes/collections/<lidvid>/members and /collections/<lidvid>/products do not return products when no paging query params are provided (should use defaults of start index 0 and 100 results - it's unclear yet whether default sorting is/should-be applied, or whether backend-internal calls are deterministic and this is not necessary)

### 🕵️ Expected behavior

I expect to see the first 100 data returned in the response

### 📜 To Reproduce

1. curl https://pds.nasa.gov/api/search/1/collections/urn:nasa:pds:orex.ovirs:data_calibrated/products
2. no results are returned despite ~1M hits and default page size100

### 🩺 Test Data / Additional context

follow-on from #231

**Comment by alexdunnjpl** [comment]
Update: For that collection, no data is returned even when supplying `start` and `limit` query params

**Comment by alexdunnjpl** [comment]
The issue is somewhat-specific to this (particularly-large at ~1.1M members) collection.  For comparison, data is returned properly for `/collections/urn:nasa:pds:mars2020_supercam:data_calibrated_audio::4.0/products`, which has only ~4k members.

Documentation states that data should be LIDVID-sorted in the absence of a user-specified sort, but this doesn't appear to be happening currently.  Unclear if this was working or not prior to #235, which changed how LIDVIDs are handled in many but not all areas of the codebase. 

![image](https://user-images.githubusercontent.com/75815303/219459965-dfc392cb-ba0c-4b51-97c5-a54133f1b4e7.png)

**Comment by alexdunnjpl** [comment]
Test script for repeatable retrieval (given constant `start` and `limit`).  Can't continue with this ticket until [broken pagination](https://github.com/NASA-PDS/registry-api/issues/240) and [lack of expected sort](https://github.com/NASA-PDS/registry-api/issues/250)is resolved.

```python
import string
from typing import List, Union

import requests

def get_ids(start: int, limit: int) -> List[str]:
    collection_urn = 'urn:nasa:pds:mars2020_supercam:data_calibrated_audio'
    url = f'http://localhost:8080/collections/{collection_urn}::4.0/products?start={start}&limit={limit}'
    print(f'Requesting start={start}, limit={limit}')
    response = requests.get(url)
    try:
        data = response.json()['data']
    except KeyError as err:
        print(f'Response for start={start}, limit={limit} did not contain a "data" attribute')
        return []

    ids = [product['id'].replace(collection_urn, '', 1) for product in data]  # for ease of visual comparison
    return ids

max_start = 5
min_limit = 1
max_limit = 5
result_end_idx = max_start + max_limit

results: List[List[Union[str, None]]] = []
for start in range(0, max_start + 1):
    for limit in range(min_limit, max_limit + 1):
        left_pad = [None]*start
        ids = get_ids(start, limit)
        padded_ids = (left_pad + ids + [None]*result_end_idx)[:result_end_idx]
        results.append(padded_ids)

for idx in range(0, result_end_idx):
    values_at_idx = set()
    for result in results:
        value_at_idx = result[idx]
        if value_at_idx is not None:
            values_at_idx.add(value_at_idx)

    assert len(values_at_idx) == 1
```

**Comment by tloubrieu-jpl** [comment]
I am closing this ticket because the related end-point is now deprecated.
