### ISSUE TITLE
Suggest: Return Content-Type application/json by default

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-api#248]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Developer, User

### 💪 Motivation

so that I can easily review responses in browser.

### 📖 Additional Details

Browsers will provide folding and syntax highlighting of JSON files.  The current default "JSON as text" HTML response breaks this and provides no value.

### Acceptance Criteria

**When I perform** browser navigation to any endpoint
**Then I expect** a properly-typed pure-JSON response

**Comment by tloubrieu-jpl** [comment]
This has been solved with commit https://github.com/NASA-PDS/registry-api/commit/13039aa3bc419114c91db96535e78d9b33be5c25
