### ISSUE TITLE
As a user, I want to see available query params in the swagger documentation

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-api#249]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

User

### 💪 Motivation

So that users can efficiently use the API.  Currently, something as simple as figuring out how to get a full set of results (with `start` and `limit` query params) requires finding the [PDS Registry documentation](https://nasa-pds.github.io/registry/index.html), finding the [Registry API link](https://nasa-pds.github.io/registry/cloud_startup.html#registry-api) (listed only under Cloud Startup and not under User Tasks, which is unintuitive to a user), and finding the link to [the API documentation](https://nasa-pds.github.io/pds-api/guides/search.html) hidden halfway down the page.

The link in the "For Data Users" at the top of the [PDS Registry documentation root](https://nasa-pds.github.io/registry/index.html) note 404s and didn't visually jump out at me (maybe a warning, rather than a note?) given that I incorrectly intuited that this was the comprehensive registry doco page.

If the swagger docs don't describe at least the minimal parameters required to perform common tasks (though preferably the full set), they're not really good for anything imho.

### Acceptance Criteria

**Given** an API endpoint
**When I perform** browser navigation to that endpoint's swagger docs
**Then I expect** to be presented with the information required to make a useful API call to that endpoint.

**Comment by tloubrieu-jpl** [comment]
I will close that ticket as fixed within the EPIC.

See screenshot:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/60993872/223507245-2b340d8b-ac29-43c3-a413-b799939e0aaa.png">
