### ISSUE TITLE
api does not return 400 error when q parameter value cannot be parsed

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#260]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I do request:

curl --request GET 'http://localhost:8081//classes/collections?q=""'

I get a 500 error.

### 🕵️ Expected behavior

I expected a 400 error with an explicit message saying the query string q is invalid and cannot be parsed.

### 📜 To Reproduce

See integration tests in repository 'registry'

### 📚 Version of Software Used

1.2.0-SNAPSHOT

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

I suugest to work on this ticket together with:
https://github.com/NASA-PDS/registry-api/issues/252
https://github.com/NASA-PDS/registry-api/issues/241 (mostly duplicate)

This requires to reintroduce invalid{Parameter}Exception

They will be catched and throw an InvalidRequestException in the processs transmutter method.

I suggest to create a super class of exception PDSAPIException to handle all the known exceptions. This will avoid to repeat all the thrown exception in the ranmute/rhandler/efLogic... methods, e.g. https://github.com/NASA-PDS/registry-api/blob/d1d0172f6147c33d6c598ceaf7052f19d63ed873/service/src/main/java/gov/nasa/pds/api/registry/controller/Member.java#L30

There was also some discussion started on that in ticket https://github.com/NASA-PDS/registry-api/issues/252

I think that would be useful to have a super type of exception,

**Comment by al-niessner** [comment]
@tloubrieu-jpl Can you post the log file exception information related to this ticket?
