### ISSUE TITLE
The members of a bundle can not be requested

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#261]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I want to see the members of a bundle:

    curl --request GET 'http://localhost:8081//products/urn:nasa:pds:insight_rad::2.1/members' \
--header 'Accept: application/json'

or 

        curl --request GET 'http://localhost:8081//products/urn:nasa:pds:insight_rad::2.1/members/members' \
--header 'Accept: application/json'

I get an error:

{
    "request": "//products/urn:nasa:pds:insight_rad::2.1/members",
    "message": "The lidvid 'urn:nasa:pds:insight_rad::2.1' of type product does not support members membership"
}

### 🕵️ Expected behavior

I expected to get the collections (/members) or the observational products/documents (/memebers/members) of the bundle 

### 📜 To Reproduce

See integration test cases in repository `registry`

### 📚 Version of Software Used

1.2.0-SNAPSHOT on main branch

### 🦄 Related requirements

🦄 #https://github.com/NASA-PDS/registry-api/issues/223

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl @jordanpadams [Related discussion](https://github.com/NASA-PDS/registry-api/issues/222#issuecomment-1367968838)

Unless something has changed, it seems like the answer here is 
 - if the error also exists for `/classes/products/{identifier}/members`, then (modify tests to) use `/classes/bundles/{identifier}/members` instead (which I personally think is a confusing requirement, but them's the breaks currently)
  - for deprecated endpoints (like `/products/...`), `members`/`memberof` subroutes are not and will not be implemented, and their equivalents aren't/won't be implemented for `/products` for the same reason as the previous bullet
