### ISSUE TITLE
the request url in the error message does not make sense

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#262]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I get an error from the API, the error message contains the request url with a double /. 

For example:
curl --request GET 'http://localhost:8081//classes/collections?q=""'

Returns:

'''
{
    "timestamp": 1677260350053,
    "status": 500,
    "error": "Internal Server Error",
    "path": "//classes/collections"
}
'''

The query parameters are also missing

### 🕵️ Expected behavior

I expected to get the absolute URL of the request in error, for example (in a development deployment):

http://localhost:8081//classes/collections?q=""

### 📜 To Reproduce

Any request generating an error

### 📚 Version of Software Used

1.2.0-SNAPSHOT on main branch

### 🦄 Related requirements

🦄 #xyz

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl Query parameters aren't strictly part of the path - should the response object contain an additional attribute `query` containing that information?

**Comment by tloubrieu-jpl** [comment]
Hi @alexdunnjpl , yes you can add the query params, I missed that indeed.
I was thinking of the double / at the beginning and the missing baseUrl, starting from http or https://

We are getting that somewhere else in the code (method getbaseurl I think) so that should be ok to do it here as well.

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl a couple of things to clarify

 - unable to reproduce - currently it returns HTTP400 Bad Request (as it seems like it should - that's an invalid path after all)
 - query params should be added to responses of the type shown in above, as agreed - do you have a reproducible example for an error with that structure?  I'm getting back html, so I wonder if there's a particular Accept header that's supposed to produce it?  `application/json` doesn't, which is what I'd have expected to use.
 - what's the motivation for including the host and scheme in the response?  If they're there, they should probably be in separate fields (they aren't part of the path), but I'm not sure why we'd bother.
 - is the fact that the path in your example contains a leading double-slash part of the undesired behaviour you're describing?  In this example it seems like correct behaviour - the requested path begins with a double-slash.

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl the error is not raised because of the path but because the q value is empty.

However, lets table this ticket for now. I realized we might not be handling the error the proper way for a restFul API, I created an EPIC in which this ticket is now.

**Comment by tloubrieu-jpl** [comment]
Re-tested today in production and with the latest developement and the request return 400 which is what we expect.

**Comment by miguelp1986** [comment]
@tloubrieu-jpl I'm receiving a 404 not 400 in Postman and in the browser. I only get a 400 when I run it in my terminal with:
`curl --request GET 'http://localhost:8081//classes/collections?q=""'`

**Comment by tloubrieu-jpl** [comment]
@miguelp1986 a bit of clarification:
- 404 is the correct error for the API service standalone because the path '//classes/collections' does not exist (not found).
- 400 is the correct error for the API service in production because in front of the API service a cloud front function clears the extra '/' which enable to find the correct path '/classes/collections' but then the q="" cannot be parsed.
- 500 was not a good error, because we want the API to fail more explicitly for the user to understand what the error was.
