### ISSUE TITLE
Add --reset flag to scheduled provenance invocation

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api#265]
According to Al N., it's advisable to incorporate the --reset flag such that all version hierarchies are rebuilt for each execution, primarily in order to ensure any recent document deletions are accounted for.

**Comment by jimmie** [comment]
This will be the 1.0.1 tag of the provenance ECR image (445837347542.dkr.ecr.us-west-2.amazonaws.com/pds-registry-provenance:1.0.1)

**Comment by jimmie** [comment]
PR is here: https://github.com/NASA-PDS/registry-api/pull/276

**Comment by tloubrieu-jpl** [comment]
Closed with PR https://github.com/NASA-PDS/registry-api/pull/276
