### ISSUE TITLE
product's members does not work on a collection

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#268]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did curl request:

    curl 'http://localhost:8081//products/urn:nasa:pds:insight_rad:data_derived::7.0/members'

I am getting the response:

```json
    {
    "request": "//products/urn:nasa:pds:insight_rad:data_derived::7.0/members",
    "message": "The lidvid 'urn:nasa:pds:insight_rad:data_derived::7.0' of type product does not support members membership"
}
```

### 🕵️ Expected behavior

I expected to get the list of observational products or documents belonging to this collection

### 📜 To Reproduce

Use the integration test setup proposed in the registry repository.

### 📚 Version of Software Used

1.2.0-SNAPSHOT on main branch

### 🩺 Test Data / Additional context

Note that same error occurs with the member-of suffix

### 🦄 Related requirements

🦄 #https://github.com/NASA-PDS/pds-api/issues/58

**Comment by tloubrieu-jpl** [comment]
This ticket blocks https://github.com/NASA-PDS/search-api-notebook/issues/6

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 🖕

**Comment by alexdunnjpl** [comment]
[Related commentary](https://github.com/NASA-PDS/registry-api/issues/261#issuecomment-1458592513)
