### ISSUE TITLE
Investigate if all fields are searchable

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#281]
## 💡 Description

Verify if https://github.com/NASA-PDS/registry-api/issues/282 and https://github.com/NASA-PDS/registry/issues/153 are done or not

**Comment by tloubrieu-jpl** [comment]
@jimmie @jordanpadams have we made progresses on this ticket ? I thought the doubt raised by @al-niessner was a false alert ? If this is confirmed we can document that here.

**Comment by jordanpadams** [comment]
@jimmie @alexdunnjpl can we confirm everything is searchable in a registry with new data ingested?

**Comment by jordanpadams** [comment]
I am thinking we pick some random attribute deep in a label and try to search for that. maybe even something from a discipline area of a label

**Comment by alexdunnjpl** [comment]
@jordanpadams I can take prioritize this, but possibly not until 03/06 (got training next week)

**Comment by jordanpadams** [comment]
per discussion at today's breakout, sample searches of semi-random metadata attributes are included in the Registry API's Postman test suite

**Comment by alexdunnjpl** [comment]
For future-me and anyone else, this is confirmed explicitly in https://github.com/NASA-PDS/registry-api/issues/287#issuecomment-1470537850
