### ISSUE TITLE
Update staging and production Registry APIs to increase window limit

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#291]
## 💡 Description

Per https://github.com/NASA-PDS/registry-mgr/issues/53 and https://github.com/NASA-PDS/registry-mgr/issues/54, we updated registry-mgr to increase the OpenSearch window limit to 1000000000. This will help resolve issues in pagination and the number of hits being displayed (https://github.com/NASA-PDS/pds-api/issues/199)

**Comment by jordanpadams** [comment]
@alexdunnjpl @jimmie can we coordinate this in the next week to see if it is works? once we set it, do we need to do anything else for it to take affect?

**Comment by alexdunnjpl** [comment]
@jordanpadams sure, though I'm not sure what I'm bringing to the table on this one

**Comment by alexdunnjpl** [comment]
@jimmie @jordanpadams any plans for this ticket?

**Comment by jordanpadams** [comment]
@alexdunnjpl this needs to be done ASAP. @jimmie how do we do this? Do we just need to run some command to update the OpenSearch config or through Kibana?

**Comment by jordanpadams** [comment]
also is this part of the Registry Terraform scripts?

**Comment by jimmie** [comment]
The result window is specified at the time the index is created - so it should be added to registry-mgr. When I did the provenance re-indexing, all max_result_window values were set to 1,000,000,000. It may have been present prior but it is certainly there now. This can be checked by examining the index: https://<opensearch_url>/registry

**Comment by jordanpadams** [comment]
thanks @jimmie

**Comment by jordanpadams** [comment]
just verified on pds-en registry:

```
..
        "provided_name" : "registry",
        "max_result_window" : "1000000000",
        "creation_date" : "1674616050693",
        "analysis" : {
          "normalizer" : {
            "keyword_lowercase" : {
              "filter" : [ "lowercase" ],
              "type" : "custom"
            }
          }
        },
```
