### ISSUE TITLE
As a EN Operator, I want to the registry API to be fault tolerant, analysis

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#297]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

EN Operator

### 💪 Motivation

...so that the API will automatically restart in the event of a crash

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
status: top of list for tuesday

**Comment by jordanpadams** [comment]
status: in work. details/options discussion at breakout

**Comment by tloubrieu-jpl** [comment]
The soution will be to create a specific healthcheck end point in the API. Ticket to be created.

**Comment by tloubrieu-jpl** [comment]
Ticket created for the development of the new feature https://github.com/NASA-PDS/registry-api/issues/336
