### ISSUE TITLE
Upgrade to OpenSearch java client

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#3]
## 💡 Description

See parent epic for all issues related to OpenSearch upgrade

**Comment by jimmie** [comment]
@tloubrieu-jpl - do we really want to close this? There is still work/planning to be done to move to OpenSearch.

**Comment by tloubrieu-jpl** [comment]
@jimmie sorry, you actually found a bug in a script I was testing to move and close epic. The dry_run is bleeding...

**Comment by tloubrieu-jpl** [comment]
@al-niessner need to look at what the impact of switching from elasticsearch client libraries to opensearch.

We shoud use opensearch 1.1

**Comment by jordanpadams** [comment]
@al-niessner latest package and info on the client can be found here: https://opensearch.org/docs/latest/clients/java-rest-high-level/ 

We want to use the latest version of this library

**Comment by tloubrieu-jpl** [comment]
The upgrade is made but some accurate tests need to be done, that will be managed in a different ticket

**Comment by tloubrieu-jpl** [comment]
This ticket is closed by PR https://github.com/NASA-PDS/registry-api/pull/104
