### ISSUE TITLE
Add github action on dev branch push, running registry integration test with docker compose

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#301]
Acceptance criteria

- [x] New github action exists
- [x] Action triggers upon PR targeting main with request-review status
- [x] Action implements the necessary elements to spin up a registry instance with `--profile=int-registry-batch-loader`, using the PR'd code for registry-api, and run [the postman tests](https://github.com/NASA-PDS/registry/blob/main/docker/postman/postman_collection.json)

Suggested trigger:

```yaml
on:
  pull_request:
    types: 
      - review_requested
    branches:
      - 'main'
```

**Comment by nutjob4life** [comment]
Maybe my local environment is mis-configured?
```
mirasol 318 % date
Wed Apr 19 16:03:39 CDT 2023
mirasol 319 % echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home
mirasol 320 % java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
mirasol 321 % mvn -version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /opt/homebrew/Cellar/maven/3.8.7/libexec
Java version: 17.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "13.3.1", arch: "x86_64", family: "mac"
mirasol 322 % git clone git@github.com:NASA-PDS/registry-api.git
Cloning into 'registry-api'...
remote: Enumerating objects: 10810, done.
remote: Counting objects: 100% (1761/1761), done.
remote: Compressing objects: 100% (629/629), done.
remote: Total 10810 (delta 880), reused 1591 (delta 777), pack-reused 9049
Receiving objects: 100% (10810/10810), 4.95 MiB | 6.98 MiB/s, done.
Resolving deltas: 100% (5688/5688), done.
mirasol 323 % cd registry-api
/tmp/registry-api
mirasol 324 % mvn spring-boot:build-image
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 4 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 4 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Registry API                                                       [pom]
[INFO] Registry API Model                                                 [jar]
[INFO] PDS API Search Query Lexer                                         [jar]
[INFO] Registry API Service                                               [jar]
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (21 kB at 29 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 20 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Registry API 1.3.0-SNAPSHOT:
[INFO] 
[INFO] Registry API ....................................... SKIPPED
[INFO] Registry API Model ................................. SKIPPED
[INFO] PDS API Search Query Lexer ......................... SKIPPED
[INFO] Registry API Service ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.069 s
[INFO] Finished at: 2023-04-19T16:04:10-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/kelly/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```
Are we sure the maven configuration is ready for this command to work, @tloubrieu-jpl?

**Comment by nutjob4life** [comment]
Testing this at … yes, it works, although it sets the "CREATED" metadata field to a weird value:
```
$ docker image ls | egrep registry-api
nasapds/registry-api                            latest              90f0e9bc7fea   43 years ago    358MB
```
Not sure what happened 43 years ago 😅

**Comment by nutjob4life** [comment]
@tloubrieu-jpl I am confused about what is actually needed here.

The title of this issue is: 

> Add github action on dev branch push, running registry integration test with docker compose

But the body of the issue says:

> Note that a docker image can be build using the maven command.
> `mvn spring-boot:build-image`
> The maven configuration is ready for this command to work.

Are these two things related?

Does this mean replacing `mvn test` with `docker-compose run reg-api-integration-test`?

And there is no `docker-compose.y*ml` file in `registry-api`. That's only in `registry`.

If you could, comment here with some help for @alexdunnjpl and myself. Or we can talk about it at the breakout meeting on 2023-04-20.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life the `mvn spring-boot:build-image` might be used to create a docker image that can be used in the docker compose, as usual. In the CICD that spares us the need to publish the jar package, which is not relevant for a branch development, or the creation of a different docker file.

But there might be an easier solution but I was proposing that so that you are aware of that option. The objective is still what the title says.

**Comment by alexdunnjpl** [comment]
@nutjob4life sounds like the gist of the Action approach discussed in the breakout amounted to

1. determine a transient tag for `registry-api` image
2. build the image from the PR code and push it to dockerhub
3. pull `registry`
4. modify env file to use transient tag for `registry-api` image
5. deploy
6. run tests with postman image (or there might be a profile that does that in one hit in the previous step, in the docker compose?)
7. break it all down and delete the transient tagged image(~is there a `finally` equivalent in github actions?~  [Looks like yes](https://docs.github.com/en/actions/learn-github-actions/expressions#always))

**Comment by nutjob4life** [comment]
@alexdunnjpl I think we can skip figuring out a transient tag because the image isn't being published, right? There's no "push it to dockerhub".

The `branch-cicd.yaml` will build the image in the local registry, run `docker compose`, and execute the tests. Then when the workflow is complete, everything goes away on its own.

1. Build the image from the PR code, enabling the default `:latest` 
2. Modify env file to use `latest`
3. `docker compose --ansi never --profile int-registry-batch-loader --project-name registry up --detach`
4. `sleep 300`
5. `exec docker compose --ansi never --profile int-registry-batch-loader --project-name registry run --rm --no-TTY reg-api-integration-test </dev/null`

Speaking of, here's how you can build the image in the local registry for step №1:
```yaml
-
    name: ☕️ Java and Maven Installation
    uses: actions/setup-java@v3
    with:
        java-version: '17'
        distribution: temurin
        cache: maven
-
    name: 💁 Get the Actions user ID
    id: user_identification
    run: |
        actions_user_id=`id --user`
        echo "uid=$actions_user_id" >> $GITHUB_OUTPUT
-
    name: 🧑‍🔧 Fix Workspace Ownership
    uses: peter-murray/reset-workspace-ownership-action@v1
    with:
        user_id: ${{steps.user_identification.outputs.uid}}
-
    name: 🚢 Docker Image Construction
    run: |
        mvn --quiet compile
        mvn --quiet spring-boot:build-image
```

**Comment by alexdunnjpl** [comment]
Oh, yeah, good point re publishing.

Suggest replacing `sleep` with something like `while docker ps | grep --quiet docker-registry-loader-test-init; do echo "something"; sleep 1; done` (for your/my reference)

**Comment by tloubrieu-jpl** [comment]
@nutjob4life @alexdunnjpl since our discussion yesterday, there are 2 things I would like to come back to:
- the integration test need to run on the code in the development branch, so it needs to be build: either before the docker image is build or build with the docker image.
- the docker image or the package does not need to be published in any artifactory. We can wait for the code to be merged in main for that to happen.

That might be obvious... I agree with th previous statement, that we don't need a transient tag, everything can be build locally as latest.

Thanks

**Comment by jordanpadams** [comment]
status: @nutjob4life portion complete. onto @alexdunnjpl. up next

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life, I believe that works, doesn't it ?

**Comment by nutjob4life** [comment]
Hi @tloubrieu-jpl: [looks like it's in](https://github.com/NASA-PDS/registry-api/blob/2af621961a9a7d5a87f49c33e6906405e1287622/.github/workflows/branch-cicd.yaml#L92).

**Comment by jordanpadams** [comment]
per the comments above, closing this ticket that has been open since October
