### ISSUE TITLE
Update to utilize new multi-tenancy approach

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#304]
## 💡 Description

- update API library
- https://github.com/NASA-PDS/registry-api/issues/422
- https://github.com/NASA-PDS/registry-api/issues/423
- https://github.com/NASA-PDS/registry-api/issues/470
- https://github.com/NASA-PDS/registry-api/issues/424

**Comment by tloubrieu-jpl** [comment]
I am starting the development to use `OpenSearchClient` object instead of `RestHighLevelClient`.
We will need that to connect to AWS OpenSearch Serverless.

**Comment by tloubrieu-jpl** [comment]
I am now block by this ticket on the java OpenSearchClient side https://github.com/opensearch-project/opensearch-java/issues/377.
Without that development, we need a java object to deserialize the documents in the database.

**Comment by tloubrieu-jpl** [comment]
I realize we can use a generic object like HashMap to deserialize the OpenSearch document.
I am moving forward with that. I was hoping to have an endpoint running with the new SDK locally today but I am still debugging that.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl status: unblocked 🎉 . marching forward now. 🤞 test endpoint ready for next week.

**Comment by tloubrieu-jpl** [comment]
test endpoint works.

**Comment by tloubrieu-jpl** [comment]
Unable to access the registry-api deployed on MCP/ECS through Load Balancer. Currently blocked by that, can discuss at the breakout or tag up scheduled tomorrow.
