### ISSUE TITLE
If >1 products with the same LIDVID are registered by different nodes, we should respond with one of them

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#306]
## 💡 Description

https://pds.nasa.gov/api/search/1/products/urn:nasa:pds:orex.spice::12.0 returns the error `Too many or too few lidvids matched the request when it should have just been 1.`.

If OpenSearch actually works with this collision, we should randomly pick one of them and this error should be alerted to the EN team, NOT to the user.

Note: Interim solution before implementing a more ubiquitous solution per https://github.com/NASA-PDS/registry/issues/93

**Comment by alexdunnjpl** [comment]
@jordanpadams what's the best way to test a fix for this?  Everything so far I've been running against a local dev instance but this needs cross-cluster.

The fix itself would be pretty trivial - change `if expect single and get multiple, then throw` to `if expect single and get multiple and len(distinct_lidvids) != 1, then throw`.

**Comment by jordanpadams** [comment]
@jimmie do we have a terraform script for CCS or a dev instance of CCS somewhere that lex can test this on?
