### ISSUE TITLE
Establish consistency between how Provenance and the API select (filter) documents by archive_status

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api#308]
This isn't technically a bug, but more an issue of being vulnerable to inconsistency.

With regards to archive_status, the API selects documents which **_have_** one of a (configurable) set of values (typically _archived, certified_). Provenance on the other hand selects documents which **_do not have_** an archive_status of _staged_ - the item of note being that in the provenance case, documents without a value for archive_status qualify. The end result is there can be a series of vids that sequentially point to a document that does have an archive_status.

When the API is looking for a product record, the query includes criteria of no value for superseded_by and archive_status of archived or certified. However, because provenance works by exclusion, we could end up with no qualifying vids for a lid (i.e. all have a superseded_by except for one that has no archive_status).

To best avoid this occurrence, provenance should request documents in the same inclusive manner as the API.

**Comment by jimmie** [comment]
Assigning to myself for now to establish visibility during stand-up.

**Comment by alexdunnjpl** [comment]
Short-term, resolved by #312 
Long-term, will be addressed by #309
