### ISSUE TITLE
Add parent bundle identifier to collection metadata

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#318]
## 💡 Description

**Create new `ops:Provenance/ops:parent_identifier` field (or `parent_bundle_identifier`) (string list)**

#### Requirements:

- the bundle-membership property shall be set for all products which are not bundles (i.e. collections and non-agg products)
- the value of the property shall enumerate the LIDVIDs of **all** "matching" bundles for the product in question.
- a "matching bundle" is defined for a collection as:
  - any bundle which references the collection explicitly by LIDVID in `ref_lid_collection`
  - any bundle which references the collection's LID or alternate_id LID
- a "matching bundle" is defined for a non-aggregate product as:
  - any bundle contained in the bundle memberships of _any_ of the non-aggregate product's parent collections

#### Requirements (obsolete)
> 
> **To populate this field for** `my_collection::1.0`:
> * First, try to query the `registry` index for a bundle that references this product by LIDVID: `product_class:Product_Bundle AND ref_lidvid_collection:"my_collection::1.0"`
>   * _I think the ref_lid_collection query should work even thought it is a list..._
> * IF nothing is returned, switch to a query the `registry` index for a bundle that references by LID: `product_class:Product_Bundle AND ref_lid_collection:"my_collection"`
> * IF still nothing, then bundle must not have been loaded yet. Maybe throw a WARNING? That way if we start to see this for a very long period of time, we know something is missing.

**Comment by alexdunnjpl** [comment]
self-note: tentative logic for not-completely-naive implementation.  Still need to work out some kinks

```

for every bundle (product_class == 'Product_Bundle') in registry:
 write null metadata
 <BUNDLES ARE COMPLETE>
 
 for every id in ref_lid_collection and ref_lid_collection_secondary:
   resolve vid (stated or latest - use lid-keyed cache for latest)
   pull collection membership metadata
   add bundle as parent bundle of collection (check distinct)
   write updated membership metadata back to collection document

<COLLECTIONS ARE COMPLETE>

for every collection in registry-refs
  pull collection's bundle membership from cache
  for each in product_lidvid
    pull product membership metadata
    add bundle and collection as parents of product (check distinct)
    write updated membership metadata back to product document

<NON-AGGs ARE COMPLETE>

Then verify
 - there are no hits in registry for product_class != 'Product_Bundle' without a bundle reference
 - there are no hits in registry for product_class not in ['Product_Bundle', 'Product_Collection'] without a collection reference
```

**Comment by alexdunnjpl** [comment]
@jordanpadams I realize you already wrote a pseudo-implementation in the issue comment, but I want to sanity-check the intended logic, and my existing understanding of what you want is slightly different, namely:

- the bundle-membership property shall be set for all products which are not bundles (i.e. collections and non-agg products)
- the value of the property shall enumerate the LIDVIDs of **all** "matching" bundles for the product in question.
- a "matching bundle" is defined for a collection as:
  - any bundle which references the collection explicitly by LIDVID in `ref_lid_collection` ~or `ref_lid_collection_secondary`~
  - any bundle which references the collection's LID or alternate_id LID ~iff no bundle satisfies the previous condition~
- a "matching bundle" is defined for a non-aggregate product as:
  - any bundle contained in the bundle memberships of _any_ of the non-aggregate product's parent collections

**Comment by jordanpadams** [comment]
@alexdunnjpl 

1. Let's ignore secondary products in this scenario. I am thinking the use case we are attempting to handle here is explicit familial member-of relationships. Secondary is kind of a "symlink" capability for a top down reference. If we want to include secondary references, we probably need to call that out as a separate attribute.

2. I think this simplifies the last bullet if we just care about explicit primary membership. We can chat more offline if needed

**Comment by alexdunnjpl** [comment]
@jordanpadams I think one last tag-up might be a good idea to refine the requirements, yeah - ignoring secondary refs doesn't change much from my side of it.

**Comment by alexdunnjpl** [comment]
Requirements ironed out with @jordanpadams, strikethroughs in earlier comment show changes.

General implementation approach approved (stateless, use registry-refs index for linking non-aggs with their collections).

**Comment by tloubrieu-jpl** [comment]
Closed per PR https://github.com/NASA-PDS/registry-sweepers/issues/14
