### ISSUE TITLE
Add parent collection identifier to product metadata

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#319]
## 💡 Description

**Create new `ops:Provenance/ops:parent_identifier` field (or `parent_collection_identifier`) (string list)**

**To populate this field for** `my_product::1.0`:
* Query the `registry` index for a collection that references this product by LIDVID: `product_lidvid:"my_product::1.0"`
* IF nothing, then collection must not have been loaded yet. Maybe throw a WARNING? That way if we start to see this for a very long period of time, we know something is missing.

**Comment by jordanpadams** [comment]
Note: waiting some help on how what field name to use, but let's go with that for now. same goes for #318

**Comment by alexdunnjpl** [comment]
[See equivalent comments in #318 ](https://github.com/NASA-PDS/registry-api/issues/318#issuecomment-1541031996) for blocking discussion.

**Comment by tloubrieu-jpl** [comment]
Closed by PR https://github.com/NASA-PDS/registry-sweepers/issues/14
