### ISSUE TITLE
Remove ./support tree from repository

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-api#321]
## 💡 Description
Provenance/support code has been migrated to https://github.com/NASA-PDS/registry-sweepers.

The code is there already, but still need to finalise release/deployment process, updated whatever docs, implement CICD automation (strictly we don't _need_ that before deletion).

@jordanpadams @jimmie what documentation do I need to update for this?

**Comment by alexdunnjpl** [comment]
@jordanpadams @jimmie @tloubrieu-jpl re-pinging on this

**Comment by alexdunnjpl** [comment]
Needs to be incorporated into docker registry repo, at the least(?)

**Comment by jimmie** [comment]
Other than in the code, I don't believe there was any documentation on provenance so this may be a good opportunity to create it in the context of the sweepers.

**Comment by jordanpadams** [comment]
@alexdunnjpl @jimmie I think since these utilities will only be run by EN, we can provide the usage documentation in the Registry Sweepers README and the explicit procedure for setting up and running the tools in the Operations portions of the EN internal Wiki.

**Comment by alexdunnjpl** [comment]
I'll open a ticket in registry-sweepers for proper documentation.

The integration into docker registry should be a one-time thing, but I'll need to take a look and figure out how best to incorporate the new dependency.

On hold until the docker registry part is complete

**Comment by alexdunnjpl** [comment]
Docker is already sorted out.

Presumably, the production ECS deployment can use the v1.0.0 image until a new release is tagged.

@jordanpadams seems like we're good to remove
