### ISSUE TITLE
Investigate how Google DataSet Search can help with the Search

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#338]
## 💡 Description

and how it could be connected to the registry-api (for example implementing this ticket  https://github.com/NASA-PDS/pds-api/issues/45).

**Comment by jjacob7734** [comment]
To use Google Dataset Search we need to add metadata in schema.org or other compatible format to the webpage as described here: https://developers.google.com/search/docs/appearance/structured-data/dataset.

**Comment by jordanpadams** [comment]
Investigation completed and added per NASA-PDS/planetary-data-engine#9
