### ISSUE TITLE
members of a bundle does not work on new test dataset

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#341]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I did request:

    http://localhost:8080/products/urn:nasa:pds:mars2020.spice::3.0/members

I am getting an empty result:

```
  "data": [
    
  ]
```

The bundle is described in opensearch with:

```
               "ref_lid_collection": [
                        "urn:nasa:pds:mars2020.spice:spice_kernels"
                    ],
                    "ref_lid_collection_secondary": [
                        "urn:nasa:pds:mars2020.spice:document"
                    ],
```

### 🕵️ Expected behavior

I expected to see at least the spice_kernel collection in the result.

### 📜 To Reproduce

Use the docker compose on registry with branch `richard_ds_198` of registry and registry-loaders repositories. 

### 🖥 Environment Info

Latest test version.

### 🦄 Related requirements

🦄 #xyz

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl there's no branch `registry:richard_ds_198` - is there supposed to be or is the suggestion to use `registry:main` and and image built from `registry-loader:richard_ds_198`?

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl I couldn't replicate due to that bundle being missing from the catalog.  Steps were:

1. Build image from  repo/branch `registry-loader:richard_ds_198`, tag as `registry-loader:richard_ds_198`
2. Modify .env to specify `REG_LOADER_IMAGE=registry-loader:richard_ds_198`
3. Run docker registry using latest `main` state, with `docker compose --profile=int-registry-batch-loader up -d`
4. Confirm that correct image was used by checking `docker events --since 180m | grep loader`

yields expected entry showing zero-code exit of container with the intended registry image

```
2023-06-08T14:52:48.838041153-07:00 container die b39606424c5bdc9236c71c9a5ec94cfc6d7d05735271a1662982907479c0f63f (com.docker.compose.config-hash=b81d61ed14c5ee1bdd4b134799b2c15048a558dab84eb9cdb1b8416600e98340, com.docker.compose.container-number=1, com.docker.compose.depends_on=, com.docker.compose.image=sha256:ae81bc06726f8a1be5e3e8e481f897fbd0eb59a3176f9bdd6c01327f8731133c, com.docker.compose.oneoff=False, com.docker.compose.project=docker, com.docker.compose.project.config_files=/nomount/registry/docker/docker-compose.yml, com.docker.compose.project.working_dir=/nomount/registry/docker, com.docker.compose.service=registry-loader-test-init, com.docker.compose.version=2.12.2, exitCode=0, image=registry-loader:richard_ds_198, name=docker-registry-loader-test-init-1)
```

5. Check API calls

```
parallels@parallels-Parallels-Virtual-Platform:~$ curl -k http://localhost:8080/products/urn:nasa:pds:mars2020.spice::3.0/members | json_pp

{
   "message" : "The lidvid 'urn:nasa:pds:mars2020.spice::3.0' of type product does not support members membership",
   "request" : "/products/urn:nasa:pds:mars2020.spice::3.0/members"
}
parallels@parallels-Parallels-Virtual-Platform:~$ curl -k http://localhost:8080/products/urn:nasa:pds:mars2020.spice::3.0 | json_pp

{
   "message" : "The lidvid urn:nasa:pds:mars2020.spice was not found",
   "request" : "/products/urn:nasa:pds:mars2020.spice::3.0"
}

```

**Comment by tloubrieu-jpl** [comment]
As a note, the members of a bundle do not work either in production https://pds.nasa.gov/api/search/1/products/urn:nasa:pds:galileo-mag-jup-calibrated::1.0/members

**Comment by tloubrieu-jpl** [comment]
Hi @alexdunnjpl ,

I merged the registry-loader pull request so you can now use registry-loader:latest image.

I was not able to reproduce your error, maybe because of something I missed to commit. We can try to reproduce that issue on your side during the breakout today.

**Comment by alexdunnjpl** [comment]
Ball is back in my court (error was due to full HDD).

Probably fixable as side-effect of #353 (pending)
