### ISSUE TITLE
Create Cloudwatch alarm when Registry API throws an error

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#366]
## 💡 Description

Follow-on to https://github.com/NASA-PDS/registry-api/issues/361, but in general, as the Registry will fail less on errors per https://github.com/NASA-PDS/registry/issues/178, we want to be able to capture those errors in the logs and notify the dev team to have a look.

**Comment by sjoshi-jpl** [comment]
@jordanpadams can we please discuss more on this in the breakout? Are we creating an alarm to monitor the Registry-API cluster, service, the task or all 3 of them?

I think task level will be more beneficial however for that we might need to enable container-insights, which is more expensive and currently only enabled for provenance. 

~$30 more per cluster * 12 clusters = $360 / month

**Comment by sjoshi-jpl** [comment]
As per latest discussions with @jordanpadams, a long term solution would be to implement a lambda which triggers when there is an ERROR in the CloudWatch logs for Registry-API and sends an email notification to Dev Team for further investigation. 

We will need SA involvement to create Lambda and Lambda Role.

**Comment by sjoshi-jpl** [comment]
Ticket created with SA team DSIO-4338 for lambda creation
