### ISSUE TITLE
Implement/reimplement ascending/descending specification for sort qparam

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-api#384]
## 💡 Description
Per old swagger docs, fields were specifiable as `asc(fieldname)` or `desc(fieldname)`.

This is not currently supported.

Implement support for `asc(fieldname)`, `desc(fieldname)` and `fieldname` (assume ascending if not specified)

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl please assess for priority

**Comment by tloubrieu-jpl** [comment]
Hi @alexdunnjpl ,

This is not in our priorities.

Thanks,

Thomas

**Comment by jordanpadams** [comment]
@alexdunnjpl as Thomas notes, we will add this to the icebox for now

**Comment by jordanpadams** [comment]
Closing this as duplicate. Created new requirement for this since we never actually documented the requirement in any of our repos. https://github.com/NASA-PDS/registry-api/issues/385
