### ISSUE TITLE
Cleanup Code Scanning Issues Identified

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#389]
## 💡 Description

- https://github.com/NASA-PDS/registry-api/issues/388
- https://github.com/NASA-PDS/registry-api/issues/387

**Comment by jordanpadams** [comment]
📆 November status: Delayed 1 sprint due to other ongoing tasks. No impact expected

**Comment by jordanpadams** [comment]
📆 December status: Delayed to later in build. No impact anticipated.

**Comment by jordanpadams** [comment]
📆 01/2024 status: In work. On schedule.

**Comment by jordanpadams** [comment]
@alexdunnjpl @tloubrieu-jpl these 2 tickets have been open for a while. Any way we can squeeze in these updates in this sprint? It is really just either pulling out these log message or modifying them slightly. Some of them don't see super critical to keep.

**Comment by jordanpadams** [comment]
📆 02/2024 status: Delayed 1 sprint. Should be able to squeeze in before delivery. No impact on build.

**Comment by alexdunnjpl** [comment]
@jordanpadams I'll sort this now

_EDIT:_ #417 #418

**Comment by jordanpadams** [comment]
thanks @alexdunnjpl
