### ISSUE TITLE
Fundamental querying logic construct appears incorrect

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-api#392]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

[Initial implementation of `GroupConstraint`](https://github.com/NASA-PDS/registry-api/commit/fe04962ddc65ede727650d43aa88c93a758aa76c#diff-42f6d9893546fc7c495731fcd9ee94d4cf81ce6a41286f383fc41d053772381c) defined methods `all()`, `any()` and `not()`, which are used to construct [OpenSearch boolean queries](https://opensearch.org/docs/1.3/query-dsl/compound/bool/) by constructing [`term` queries](https://opensearch.org/docs/1.3/query-dsl/term/term/) under `must`, `filter` and `mustnot` query attributes, respectively. [Initial implementation of that logic is here](https://github.com/NASA-PDS/registry-api/blob/fe04962ddc65ede727650d43aa88c93a758aa76c/service/src/main/java/gov/nasa/pds/api/registry/model/ProductQueryBuilderUtil.java#L102-L119)

The Java methods [were later renamed](https://github.com/NASA-PDS/registry-api/pull/328/commits/c114abf413820090ae4720eb618776d44e142bde) to `must`/`filter`/`mustNot`, to reflect and communicate the OpenSearch concepts they were leveraging.

If the intent of `GroupConstraint.any` is to provide a mapping of keywords `K` onto value-sets `V_k` such that any document having a value in `V_k` for any property `K` (or all properties `K` - it's not clear what the nested logic is intended to be in the case of multiple `K`s), the [current use of OpenSearch's `filter` to implement `any()`](https://github.com/NASA-PDS/registry-api/blob/fe04962ddc65ede727650d43aa88c93a758aa76c/service/src/main/java/gov/nasa/pds/api/registry/model/ProductQueryBuilderUtil.java#L112) is incorrect, resulting in the following:

Currently, given a `GroupConstraint` with `any = {"P": ["A", "B"]}`, the result of building a query with that constraint is something like

```JSON
{
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "P": {
                            "value": "A",
                            "boost": 1.0
                        }
                    }
                },
                 {
                     "term": {
                         "P": {
                             "value": "B",
                             "boost": 1.0
                         }
                     }
                 }
            ]
    },
}
```

however this will never match anything unless a document has both `A` and `B` in `P` (which is technically possible, given that `P` will be an array, but I can't imagine that was the intent) The query producing the desired result will actually be

```JSON
{
    "query": {
        "bool": {
            "filter": [
                {
                    "terms": {
                        "P": ["A", "B"]
                     }
                 }
            ]
    },
}
``` 

If my understanding of the intended functionality is correct, I suggest:
- renaming `GroupConstraint.filter()` back to `GroupConstraint.any()`
- clarifying and documenting how it is supposed to work when given multiple keywords, like `{"P1": ["A1", "B1"], P2": ["A2", "B2"]}`
- correcting [the way in which is is used to build queries](https://github.com/NASA-PDS/registry-api/blob/fe04962ddc65ede727650d43aa88c93a758aa76c/service/src/main/java/gov/nasa/pds/api/registry/model/ProductQueryBuilderUtil.java#L112)

@al-niessner, @jordanpadams, @tloubrieu-jpl, could one of y'all please clarify the intended behaviour of `GroupConstraint.any()`?

**Comment by alexdunnjpl** [comment]
Blocks #353

**Comment by jordanpadams** [comment]
@tloubrieu-jpl I think this is tied to all of the other API work you are doing.

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl @jordanpadams suggest closing this ticket as obsolete/stale - there's no reason for these constructs to stick around post-overhaul, right?

**Comment by jordanpadams** [comment]
Closed as invalid
