### ISSUE TITLE
cicd fails on registry-api-service

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#4]
![image](https://user-images.githubusercontent.com/60993872/145908592-8adc1936-72e8-4069-82f7-803994c542af.png)

See for detals action https://github.com/NASA-PDS/registry-api-service/actions/runs/1575429493

**Comment by tloubrieu-jpl** [comment]
transferred from obsolete registry-api-service

**Comment by jordanpadams** [comment]
@tloubrieu-jpl fyi, there is a `Move` capability within GitHub that tends to be a little cleaner than the `Transfer` capability provided by Zenhub. Not a big deal but just a heads up.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams ok, I will do that. thank you your feedback on that, I did not read down enough...

**Comment by jordanpadams** [comment]
this has been fixed and CICD now works on new repo
