### ISSUE TITLE
members query return 500 when members do not exist in the registry or alternate_id does not exists

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#411]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did the request:
https://pds.nasa.gov/api/search/1.0/products/urn:nasa:pds:cassini_iss_cruise:xml_schema::1.0/members

I got a 500 error.

### 🕵️ Expected behavior
I expected to get the members of the collection.  As it does with request https://pds.nasa.gov/api/search/1.0/products/urn:nasa:pds:orex.ovirs:data_calibrated::11.0/members

### 🖥 Environment Info

- Version of this software 1.4.0 deployed in production

### 🩺 Test Data / Additional context

See cloudwatch logs at 2024-02-26T22:31:52.081-05:00:

2024-02-27T03:31:52.079Z ERROR 1 --- [-nio-80-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException] with root cause

### 🦄 Related requirements

🦄 #xyz

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl It sounds like the error comes from the code expecting alternate_ids to find the ancestor whereas alternate_ids are not always available.
See line https://github.com/NASA-PDS/registry-api/blob/e254a442fe4c04a1fbf798899318c3eef7ef2e6d/service/src/main/java/gov/nasa/pds/api/registry/model/RefLogicCollection.java#L57

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @alexdunnjpl for this collection, it looks like it contains all secondary references, of which, those products have not yet been registered.
https://pds-rings.seti.org/pds4/bundles/cassini_iss_cruise//xml_schema/collection_xml_schema.xml
https://pds-rings.seti.org/pds4/bundles/cassini_iss_cruise//xml_schema/collection_xml_schema.csv

**Comment by tloubrieu-jpl** [comment]
@jordanpadams, I am meeting with @alexdunnjpl to confirm before our Registry workshop this morning.

**Comment by tloubrieu-jpl** [comment]
Alternate ids has been added by the following commit https://github.com/NASA-PDS/registry-common/commit/a08168e1949535a8d7d7845e49cf304221da06fd

First release in registry-common/1.2.0 (see https://github.com/NASA-PDS/registry-common/releases/tag/v1.2.0).

Used in harvest v3.6.0 and after (but not before).

This is confirmed by the kibana visualization here:

<img width="1079" alt="image" src="https://github.com/NASA-PDS/registry-api/assets/60993872/c4ce9c70-7ea1-4f34-b2cc-a8dda0c75855">

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl I believe you can start looking at a development in sweepers to add an alternate_ids when it is missing.

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl if alternate_ids is just "the lid plus the lidvid" and it doesn't even provide the added value of tracking renames, is there any point to maintaining it?

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl , the intention was to use it for renamed lids as well, but I am not sure where we are with that. We can discuss that during the breakout today.

**Comment by tloubrieu-jpl** [comment]
We decided during the breakout to change the registry-api code to not use anymore the alternate_ids but the actual identifier (_id or lidvid).

@alexdunnjpl is analyzing this fix.
