### ISSUE TITLE
As a user, by default, I want to search only for the latest versions of all products on the `/products` endpoint

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#426]
## 💪 Motivation
...so that I am not confused by seeing superseded data returned in search results

## 📖 Additional Details

Per the [parent epic](https://github.com/nasa-pds/pds-registry-app/issues/219), and [the design](https://github.com/nasa-pds/pds-registry-app/issues/229) we need to update the API to implement these changes so we can sufficiently understand the version history.

See parent epic for more details.

## ⚖️ Acceptance Criteria
**AC 1:**
**Given** the products `urn:nasa:pds:mars2020.spice::1.0`, `urn:nasa:pds:mars2020.spice::2.0`, and `urn:nasa:pds:mars2020.spice::3.0` have been loaded into the registry (see registry-ref-data) and in `archived` status
**When I perform** a query of the API for `/products` and paginate through the results and/or apply any other filtering that would include this SPICE bundle
**Then I expect** I should get only the latest v3.0 product returned (`urn:nasa:pds:mars2020.spice::3.0`)

**AC 2:**
**Given** the products `urn:nasa:pds:mars2020.spice::1.0`, `urn:nasa:pds:mars2020.spice::2.0`, and `urn:nasa:pds:mars2020.spice::3.0` have been loaded into the registry (see registry-ref-data) and in `archived` status
**When I perform** a query of the API for `/products/urn:nasa:pds:mars2020.spice::1.0`
**Then I expect** I should get the older version 1.0 of the product (`urn:nasa:pds:mars2020.spice::1.0`) because it was explicitly requested

**AC 3:**
_Note: This AC depends upon the completion of this requirement: https://github.com/NASA-PDS/registry-api/issues/427_
**Given** the context products [urn:nasa:pds:context:instrument:crs.vg1::1.0](https://pds.nasa.gov/data/pds4/context-pds4/instrument/vg1.crs_1.0_deprecated.xml) and [urn:nasa:pds:context:instrument:vg1.crs::1.0](https://pds.nasa.gov/data/pds4/context-pds4/instrument/vg1.crs_1.0.xml) ingested into the registry
**When I perform** a query of the API for `/products` and paginate through the results, or perform any additional filtering on the data
**Then I expect** I should only see the product metadata for [urn:nasa:pds:context:instrument:vg1.crs::1.0](https://pds.nasa.gov/data/pds4/context-pds4/instrument/vg1.crs_1.0.xml) returned, not the superseded/deprecated [urn:nasa:pds:context:instrument:crs.vg1::1.0](https://pds.nasa.gov/data/pds4/context-pds4/instrument/vg1.crs_1.0_deprecated.xml)

## ⚙️ Engineering Details

See parent ticket for related requirements:
- https://github.com/NASA-PDS/registry-api/issues/428

**Comment by jordanpadams** [comment]
alternate_ids implemented but we now need to build this into the API so we use this field and date time to properly support version histories.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @al-niessner I believe it will be better to wait for the redesign to be completed before working on that.

**Comment by jordanpadams** [comment]
@alexdunnjpl just want to confirm that this has a test in the test suite and can be closed alongside #503 #487 #484 #485 #486 ?

**Comment by alexdunnjpl** [comment]
@jordanpadams There is not a distinct test for this issue, but coverage (of the common code path subsetting a result set to non-superseded products) is provided by the new tests for those tickets.
