### ISSUE TITLE
ECS Roles for Registry-API

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry-api#429]
### 💡 Description

We need to create an ECS Task execution Role and an ECS Task Role with access to OpenSearch Serverless Service for Read access.

**Comment by jordanpadams** [comment]
status: Mostly done, but discussion planned with @tloubrieu-jpl to review further.

**Comment by tloubrieu-jpl** [comment]
We now need to clean the roles and security groups.

**Comment by jordanpadams** [comment]
Closed. These have been completed in Dev
