### ISSUE TITLE
Investigate sporadic 500 and 504 errors with registry API

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#431]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I tried TBD queries, I was getting sporadic 504 errors.

<img width="725" alt="Screenshot 2024-04-11 at 9 13 45 AM" src="https://github.com/NASA-PDS/registry-api/assets/33492486/3b7f601c-0029-4053-8a91-d95d31dc7ddb">

### 🕵️ Expected behavior

I expected the API to work

### 📜 To Reproduce

TBD queries

See CloudFront and/or Registry logs.

### 🖥 Environment Info

latest deployed

**Comment by tloubrieu-jpl** [comment]
Here are the 100 requests which came to the API when the instability was noticed:
[7a541e10-8113-44f6-9bd1-f58951c81317.csv](https://github.com/NASA-PDS/registry-api/files/14952110/7a541e10-8113-44f6-9bd1-f58951c81317.csv)

the first errors came up after limit parameter was set to 10000 which can work, and worked in later tests but is above what we would expect (a few 100s).

The issue might also be related to simultaneous activities on the registry (e.g. sweepers).

**Comment by jordanpadams** [comment]
Similar issue identified by @anilnatha attempting the following query: 
```
https://pds.nasa.gov/api/search/1/products?q=(product_class eq "Product_Context" and lid like "urn:nasa:pds:context:instrument_host:*")&limit=9999&fields=lid,vid,pds:Instrument_Host.pds:description,pds:Instrument_Host.pds:name,pds:Instrument_Host.pds:type
```

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @alexdunnjpl for this issue, if we know the page size is too large, is there any way we can improve the error messaging that comes with these errors? Or is this a server timeout thing?

**Comment by alexdunnjpl** [comment]
@jordanpadams server timeout if it's what I think it is - basically the request is valid and reasonable prima facie, but then the volume (size, not count) of the data ends up taking too long to serve so the server calls it quits.

This could be confirmed by repeating the queries, limiting the requested fields to `lidvid` to ensure no large data volume is served, assuming the issues aren't so sporadic that you're unable to convince yourself that it's working without issue after some reasonable period of testing.

**Comment by jordanpadams** [comment]
@alexdunnjpl copy. is there any way we can do some other smart things on the API side to either keep the connection alive with the server?

**Comment by alexdunnjpl** [comment]
@jordanpadams I wouldn't think so (without a box full of bandaids or increasing timeout thresholds) - from my perspective it's on the client to respond appropriately to a 504 (by, for example, retrying with a smaller request)

I haven't dug into what's going on here, though - I'm making some assumptions.

**Comment by jordanpadams** [comment]
thanks @alexdunnjpl we will dig a bit further in the future to see what we can do. The problem here being with an internet browser and curl as clients, there is nothing to do there in terms of responding to this appropriately. We may just need to update the documentation to explicitly call out these errors.

**Comment by tloubrieu-jpl** [comment]
We will see if that comes up again.

We could limit the page size by forbidding queries with too large pages but the page size acceptable might differ depending on the type of query, e.g. with more or less fields. 

The best solution might be to add help in a github discusions. Discussion added and closed: https://github.com/NASA-PDS/registry-api/discussions/521

**Comment by tloubrieu-jpl** [comment]
Maybe we should have the gateway (frontend time out) match the back-end (ECS fargate time outs). I don't know how that can be done.

**Comment by jordanpadams** [comment]
Skipping I&T. Too difficult to test sporadic issues. Received indication from end users these no longer occur

**Comment by jordanpadams** [comment]
Documentation added to Discussion Board
