### ISSUE TITLE
As a user, I want to get all product versions associated to one lid

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#436]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data user.

### 💪 Motivation

...so that I can see all available version related to a lid

### Acceptance Criteria

**Given** a lid {lid}
**When I perform** a request /products/{lid}/all
**Then I expect** to get all the products having this lid

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @alexdunnjpl per our conversations with IMG a couple months ago, since we are moving towards adding additional endpoints like:

```
/products/{identifier}/services
/products/{identifier}/targets
/products/{identifier}/instruments
etc.
```

Did we want to change the all functionality to be a new `version` query parameter instead? Something like:

```
/products/{identifier}?version=all
/products/{identifier}?version=1.0
/products/{identifier}?version=1.1
/products/{identifier}?version=latest
```

or maybe just more of a flag?
```
/products/{identifier}?versions=all
/products/{identifier}?versions=latest

/products/{identifier}?all-versions=true
```

**Comment by tloubrieu-jpl** [comment]
Yes @jordanpadams , I thought of it but I figured we can keep that for after the migration as-is is complete, actually we will also do (not part of this requirement though)
`/products?q=....&keywords=...&versions=all`

For the specific versions of a lid, I was thinking we would keep the version part of the identifier. I prefer your latest options actually : `/products/{identifier}?all-versions=true`, that makes the behavior easier to understand for users I think.

**Comment by alexdunnjpl** [comment]
One vote for `version=1.0`, `version=latest`, `version=all`

If you keep one parameter name for "specify the version(s)", I think that's more easily-remembered for users, and it also allows for a single common handler under the hood to turn that qparam into an element of the opensearch query.

**Comment by alexdunnjpl** [comment]
I agree with @tloubrieu-jpl that there's no reason to request a LID with a specific version specifier qparam when the LIDVID is trivially constructable.

If the default case is latest-only across the API and this is well-understood by users, I think that `all-versions=true` is a reasonable approach.

My only outstanding question is whether there's ever a use-case where a used might provide a LIDVID, and desire the latest version of the product without knowing the VID?  If so, then a `version=latest` and `version=all` qparam would be preferable, imho.

**Comment by jordanpadams** [comment]
@alexdunnjpl @tloubrieu-jpl either works for me. The last use case you mentioned is not a unrealistic possibility.

**Comment by tloubrieu-jpl** [comment]
I will close this ticket since the requirement is implemented in the develop branch.
I'll create a new ticket for the `all-version` parameter implementation.
