### ISSUE TITLE
As an API user, I want to search by a temporal range as an ISO-8601 time interval.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#465]
## Motivation
...so that I can find data within some notional time.

## Additional Details

The API enables this out of the box. This issue is really just to document how to do it.

For example: https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#temporal-range-searches

Should we enable "fuzzy" temporal ranges (e.g. datetime ge 2017)? or maybe that is a separate ticket and we wait to see if people are actually upset about requiring  ISO 8601 time intervals.

## Acceptance Criteria
**Given** a deployed API server
**When I perform** A request with time criteria as follow, for example 

`curl --location --request GET 'http://localhost:8080/products?&q=((pds:Time_Coordinates.pds:start_date_time gt "2018-05-04T00:00:00Z") and (pds:Time_Coordinates.pds:start_date_time lt "2018-05-06T00:00:00Z"))'`

**Then I expect** a result where the start_date_time property matches the criteria

Note that the postman collection is updated with this test`NASA-PDS/pds-api#72` in  https://github.com/NASA-PDS/registry/blob/main/docker/postman/postman_collection.json

## Engineering Details

Should require  ISO-8601 time intervals.

**Comment by tdddblog** [comment]
Boolean operators and parenthesis are broken in current query lexer / parser implementation, therefore range queries which require `AND` operator do not work.
I had to fix lexer (https://github.com/NASA-PDS/api-search-query-lexer/pull/6) and API Service (https://github.com/NASA-PDS/registry-api-service/pull/72) projects.

**Comment by jordanpadams** [comment]
will revert https://github.com/NASA-PDS/api-search-query-lexer/pull/6 and update https://github.com/NASA-PDS/registry-api-service/pull/72 to use the changes we will introduce to use the `like` wildcard query.
