### ISSUE TITLE
As a user, I want to filter the products by any available PDS4 property using a combination of comparison, logical, and precedence grouping operators

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#469]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data user

### 💪 Motivation

...so that I can perform very specific searches for very granular metadata values

### 📖 Additional Details

See [Query String Operators](https://github.com/NASA-PDS/pds-api/blob/main/docs/spec/pds-api-specification.md#query-string-operations) in the spec for expected supported operators.

### Acceptance Criteria

**Given** a registry loaded with data where investigation is Mars 2020, and `pds:start_date_time` is intersects the time range `2022-05-10T00:00:00Z` to `2023-05-10T00:00:00Z`
**When I perform** `/some/endpoint?q=(ref_investigation eq "urn:nasa:pds:context:investigation:mission.mars2020" AND (pds:Time_Coordinates.pds:start_date_time gt "2022-05-10T00:00:00Z" AND pds:Time_Coordinates.pds:start_date_time lt "2023-05-10T00:00:00Z"))`
**Then I expect** the data products from Mars 2020 between the expected time range to be returned in the result set

### ⚙️ Engineering Details

Pre-requisite requirements:
* 🦄 #494 
* 🦄 #495

**Comment by jordanpadams** [comment]
@tloubrieu-jpl should this be re-assigned to @alexdunnjpl ?

**Comment by tloubrieu-jpl** [comment]
This ticket can be closed as it is implemented in the develop branch.
