### ISSUE TITLE
As a user, by default, I want to search for the latest versions of all products on the `/classes/{class}` endpoint unless explicitly requested

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#488]
### Checked for duplicates

No - I haven't checked

### 💪 Motivation

...so that I can get all applicable products of a specific product class, but avoid getting any superseded data.

### 📖 Additional Details

dependent upon https://github.com/NASA-PDS/registry-api/issues/511

### Acceptance Criteria

NOTE: These acceptance criteria are just for example. See #511 for all the possible product classes you could use as test cases

**Given** multiple versions of a `Product_Collection` product
**When I perform** `GET /classes/collections`
**Then I expect** when paginating through the results, I get only the latest version of that collection product

**Given** multiple versions of a `Product_Browse` product loaded into the registry
**When I perform** `GET /classes/browses`
**Then I expect** when paginating through the results, I get only the latest version of that browse product

**Given** multiple versions of a `Product_Observational` product loaded into the registry
**When I perform** `GET /classes/observationals`
**Then I expect** when paginating through the results, I get only the latest version of that observational product

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl this endpoint does not appear to be reimplemented yet - shall I go ahead with that?

**Comment by jordanpadams** [comment]
@alexdunnjpl yes. I will create a requirement

**Comment by jordanpadams** [comment]
@alexdunnjpl new requirements created: #511

**Comment by alexdunnjpl** [comment]
@jordanpadams the scope of these "latest unless specifically-requested" reqs does not include implementation of the feature "user can specifically request all versions", yeah?

**Comment by jordanpadams** [comment]
@alexdunnjpl correct. Those will be separate requirements when the time comes
