### ISSUE TITLE
As a user, I want to apply an additional query filter (`q=`) to the `/products/{identifier}/member-of` result set

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#491]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User

### 💪 Motivation

...so that I can search for the the bundle of a collection or collection of a product, and then provide additional filters to the search within that result set.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
That is validated from PR https://github.com/NASA-PDS/registry-api/pull/526
