### ISSUE TITLE
As a user, I want to apply an additional query filter (`q=`) to the `/classes/{class}` result set

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#493]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User

### 💪 Motivation

...so that I can search for the products of a particular class, and then provide additional filters to the search within the result set.

### Acceptance Criteria

**Given** two `Product_Collection` products `collection_x::1.0` with target Mars, `collection_y::1.0` with target Moon loaded into the registry
**When I perform** `GET /classes/collections?q=(ref_lid_target eq 'urn:nasa:pds:context:target:planet.mars'`
**Then I expect** product `collection_x::1.0` to be in the result set

**Comment by alexdunnjpl** [comment]
@jordanpadams this is already implemented in https://github.com/NASA-PDS/registry-api/pull/512

https://github.com/NASA-PDS/registry-api/pull/512/files#diff-86005b9ee122b899829313c52db78ee498ab2100bdd096d31ebcb06c1bc10d6dR623

As far as tests go, I'd suggest a test for each dot-method and implementing https://github.com/NASA-PDS/registry-api/issues/515 to eliminate the need to test each endpoint's use of already-implemented behaviour

**Comment by alexdunnjpl** [comment]
@jordanpadams am I good to close this issue?

**Comment by alexdunnjpl** [comment]
Context: reopened, I assume, due to outstanding discussion to be had over required granularity of test-cases

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl is the plan to cover this at today's breakout?

**Comment by tloubrieu-jpl** [comment]
Yes @alexdunnjpl , we can discuss it

**Comment by alexdunnjpl** [comment]
reassigned to Thomas for disposition

**Comment by tloubrieu-jpl** [comment]
validated with new test in PR https://github.com/NASA-PDS/registry/pull/313
