### ISSUE TITLE
As a user, I want to filter the products by any available PDS4 property using comparison operators

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#494]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User

### 💪 Motivation

...so that I can query very specific values based upon comparison operators

### 📖 Additional Details

Supported comparison operators: `eq`, `ne`, `gt`, `ge`, `lt`, `le`

## AC1
**Given** a registry loaded with a subset of data with a target of Mars
**When I perform** `/some/endpoint?q=(ref_target eq "urn:nasa:pds:context:target:planet.mars")`
**Then I expect** the result set to contain all expected products where target **is Mars**

## AC2
**Given** a registry loaded with a subset of data with a target of Mars and other targets
**When I perform** `/some/endpoint?q=(ref_target ne "urn:nasa:pds:context:target:planet.mars")`
**Then I expect** the result set to contain all expected products where target is **NOT Mars**

## AC3
**Given** a registry loaded with a subset of data with times before and after `2001-05-10T00:00:00Z`
**When I perform** `/some/endpoint?q=(
pds:Time_Coordinates.pds:start_date_time gt "2001-05-10T00:00:00Z")`
**Then I expect** the result set to contain all expected products where `pds:start_date_time` is **after** `2001-05-10T00:00:00Z`

## AC4
**Given** a registry loaded with a subset of data with `pds:start_date_time` before and after `2001-05-10T00:00:00Z`
**When I perform** `/some/endpoint?q=(
pds:Time_Coordinates.pds:start_date_time lt "2001-05-10T00:00:00Z")`
**Then I expect** the result set to contain all expected products where `pds:start_date_time` is **before** `2001-05-10T00:00:00Z`

## AC5
**Given** a registry loaded with a subset of data with `pds:start_date_time` before, after, and **exactly matches** `2001-05-10T00:00:00Z`
**When I perform** `/some/endpoint?q=(
pds:Time_Coordinates.pds:start_date_time ge "2001-05-10T00:00:00Z")`
**Then I expect** the result set to contain all expected products where `pds:start_date_time` is **after** `2001-05-10T00:00:00Z` **and equals** `2001-05-10T00:00:00Z`

## AC6
**Given** a registry loaded with a subset of data with `pds:start_date_time` before, after, and **exactly matches** `2001-05-10T00:00:00Z`
**When I perform** `/some/endpoint?q=(
pds:Time_Coordinates.pds:start_date_time le "2001-05-10T00:00:00Z")`
**Then I expect** the result set to contain all expected products where `pds:start_date_time` is **before** `2001-05-10T00:00:00Z` **and equals** `2001-05-10T00:00:00Z`

**Comment by tloubrieu-jpl** [comment]
Need to add test for each acceptance criteria.

**Comment by alexdunnjpl** [comment]
Tests added in https://github.com/NASA-PDS/registry/pull/311
