### ISSUE TITLE
As a user, I want to filter the products by any available PDS4 property by combining comparison operators using logical operators

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#495]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User

### 💪 Motivation

...so that I can combine comparison operations for more complex queries

### 📖 Additional Details

Logical operators supported: `and`, `or`, `not`

## AC1
**Given** a registry loaded with a subset of data with target of Mars and investigation is Mars2020 plus some other investigations
**When I perform** `/some/endpoint?q=(ref_target eq "urn:nasa:pds:context:target:planet.mars" AND ref_investigation eq "urn:nasa:pds:context:investigation:mission.mars2020")`
**Then I expect** the result set to contain all expected products where **target is Mars** and **investigation is Mars 2020**

## AC2
**Given** a registry loaded with a subset of data with investigation is Mars2020 or Mars Science Laboratory plus some other investigations
**When I perform** `/some/endpoint?q=(ref_investigation eq "urn:nasa:pds:context:investigation:mission.mars2020" OR ref_investigation eq "urn:nasa:pds:context:investigation:mission.mars_science_laboratory")`
**Then I expect** the result set to contain all expected products where **investigation is Mars 2020** OR **investigation is Mars Science Laboratory**

## AC3
**Given** a registry loaded with a subset of data with investigation is Mars2020 or Mars Science Laboratory plus some other investigations
**When I perform** `/some/endpoint?q=(ref_investigation eq "urn:nasa:pds:context:investigation:mission.mars2020" OR ref_investigation eq "urn:nasa:pds:context:investigation:mission.mars_science_laboratory")`
**Then I expect** the result set to contain all expected products where **investigation is Mars 2020** OR **investigation is Mars Science Laboratory**

## AC1
**Given** a registry loaded with a subset of data with target of Mars and investigation is Mars2020 plus some other investigations
**When I perform** `/some/endpoint?q=(NOT ref_investigation eq "urn:nasa:pds:context:investigation:mission.mars2020")`
**Then I expect** the result set to contain all expected products where **investigation is NOT Mars 2020**

**Comment by tloubrieu-jpl** [comment]
I believe the boolean operators are currently in lower case (or, and, not) as well as the comparison operators (eq, lt, ...)

**Comment by alexdunnjpl** [comment]
@jordanpadams given Thomas' comment, is there anything to do here?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @alexdunnjpl do we want to be case-sensitive with these operators?

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl in the interests of user-friendliness I guess not.
