### ISSUE TITLE
AWS cost analysis tag  is not 'Alpha' but instead 'Alfa'

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api#5]
## 🐛 Describe the bug
The terraform scripts are employing an AWS tag 'Alpha' as one of the cost tags, however the correct spelling is 'Alfa'. This is making it difficult (but not impossible) to identify nodes in CUR queries (since the Alfa tag is used to store the node name).

## 📜 To Reproduce
1) Check terraform scripts - see references to 'Alpha' tag and assigned the node name abbreviation
2) As the cost_analysis role, open the Athena query editor: https://console.aws.amazon.com/athena/home?region=us-east-1#/query-editor
3) Examine the schema for the default_445837347542 table (which stores the CUR information), note the column 'resource_tags_user_alfa' (which is assigned the value of the 'Alfa' tag).
4) Optionally query this column value, note that it is empty.

## 🕵️ Expected behavior
The resource_tags_user_alfa column should contain the node name abbreviation.

## 📚 Version of Software Used
0.4.1 and 0.5.0

**Comment by tloubrieu-jpl** [comment]
closed by mistake

**Comment by jimmie** [comment]
PR request approved and merged by Jordan.
