### ISSUE TITLE
Implement the all/latest version requirement with a query parameter

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#502]
### 💡 Description

The new query parameter is "all-versions". the values can be 'true' or 'false'. The parameter is optional, default behavior is all-versions=false. Or actually we could see that the other way around `latest-only=true` by default.

This behavior will replace the suffix `/latest` or  `/all`  to implement the requirement https://github.com/NASA-PDS/registry-api/issues/436 and should be extended to apply to all end-points.

**Comment by jordanpadams** [comment]
Duplicate of https://github.com/NASA-PDS/registry-api/issues/428
