### ISSUE TITLE
As a user, I want to know what are all the possible properties I can search against (`/properties`)

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#506]
### Checked for duplicates

No - I haven't checked

### 💪 Motivation

...so that I can know all the available properties I can search by in the API.

### Acceptance Criteria

**Given** a running API service
**When I perform** `GET /properties`
**Then I expect** to receive the set of all properties available for search within the system

### ⚙️ Engineering Details

Note: This is a first barebones pass and what is returned by this endpoint. A more robust, detailed response will eventually be needed in order to support a more useful response (e.g. definitions)

**Comment by alexdunnjpl** [comment]
@jordanpadams is this endpoint intended to ever support subsetting, or is it sufficient to (more or less) dump the union of all registry indices' `_mapping` content?

**Comment by jordanpadams** [comment]
@alexdunnjpl I think for now a dump of the _mapping works for now. We probably want a smarter version of this that actually pulls information from the PDS4 Information Model, but I think for now, just a top of what is searchable will do.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl ☝️
