### ISSUE TITLE
Investigate why the API is slow on MCP

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#510]
### 💡 Description

For example the following request, with no cache took more that 1 minute:

% date;curl --header 'Accept:application/json' 'http://registry-api-lb-new-580211398.us-west-2.elb.amazonaws.com/products?limit=3' | json_pp; date
Mon Jul 22 17:45:42 EDT 2024
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 73889    0 73889    0     0    970      0 --:--:--  0:01:16 --:--:-- 20837

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl Unable to replicate - locally, on VPN, first run takes ~1sec

Are you still experiencing this issue?
