### ISSUE TITLE
Fix code scanning alerts per logging

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#522]
Tracking issue for:
- [ ] https://github.com/NASA-PDS/registry-api/security/code-scanning/155

Per https://github.com/NASA-PDS/registry-api/blob/develop/service/src/main/java/gov/nasa/pds/api/registry/search/RegistrySearchRequestBuilder.java#L309:

Is this sanitized prior to logging?

**Comment by jordanpadams** [comment]
@alexdunnjpl any idea if this query string is sanitized prior to logging?

https://github.com/NASA-PDS/registry-api/blob/develop/service/src/main/java/gov/nasa/pds/api/registry/search/RegistrySearchRequestBuilder.java#L309

**Comment by alexdunnjpl** [comment]
merged to `develop`

**Comment by jordanpadams** [comment]
Skipping I&T. Internal logging updates. Inspected on PR merge
