### ISSUE TITLE
Revert  ES High Level Java API version 7.13.3

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#6]
@jimmie commented on [Fri Dec 10 2021](https://github.com/NASA-PDS/registry-api-service/issues/97)

Version 7.15.1 of the ES High Level Java API will not work with AWS's ES 7.10 due to the latter's incompatible build flavor ('oss' vs 7.15.1's expected 'default'). We need to revert back to 7.13.3 of the API in order to be able to deploy the registry on AWS.

The impact of this appears to be changing the package of the TimeValue class in the imports in two locations, it does not seem any 7.15.x specific features are in use.

---

@tloubrieu-jpl commented on [Wed Jan 05 2022](https://github.com/NASA-PDS/registry-api-service/issues/97#issuecomment-1005852328)

@jimmie is this ticket ok to be closed ?

I am move it open to registry-api repository, but feel free to close it it done

**Comment by jimmie** [comment]
This has been addressed w/ the latest release.
