### ISSUE TITLE
add creation of routing rule to terraform script

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#7]
@jimmie commented on [Wed Dec 08 2021](https://github.com/NASA-PDS/registry-api-service/issues/95)

Routing rules tell the AWS load balancer (listener) to which target group to send incoming requests. This also associates the target group w/ the load balancer (which is needed in order for the service to be created successfully). Add the creation of this rule to the ecs.tf terraform script.

**Comment by jimmie** [comment]
[PR #96](https://github.com/NASA-PDS/registry-api-service/pull/96) in registry-api-service was approved and merged in early December. Closing this issue.
