### ISSUE TITLE
Update API to only return results where archive status in (archived, certified)

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#78]
See related requirements below. With archive_status set, we want to block access to only data that is archived and release.

## Related Requirements
🦄 https://github.com/nasa-pds/pds-api/issues/106

**Comment by tloubrieu-jpl** [comment]
closed by mistake

**Comment by tdddblog** [comment]
@jordanpadams @tloubrieu-jpl "archived" only or both  "archived" and "certified" as described in "Discussion from SWG" document?

**Comment by jordanpadams** [comment]
@tdddblog Archived and certified! Thanks for checking on that

**Comment by tloubrieu-jpl** [comment]
@tdddblog 
I was thinking the configuration for which products status should be published through the API would be in the `application.properties` file. That might be obvious but I prefer to be explicit. Thanks

**Comment by jordanpadams** [comment]
resolved per https://github.com/NASA-PDS/registry-api/pull/99
