### ISSUE TITLE
LID -> LIDVID conversion not consistent in registry-api

### ISSUE THREAD

**Issue by al-niessner** [NASA-PDS/registry-api#79]
## 🐛 Describe the bug
There are two independent [LidVidDAO](https://github.com/NASA-PDS/registry-api/blob/a72b40eee36a6cea953a2a9e7ed3ffc0b4c0b649/service/src/main/java/gov/nasa/pds/api/engineering/elasticsearch/business/LidVidDAO.java) and [PropertyBusinessObject](https://github.com/NASA-PDS/registry-api/blob/a72b40eee36a6cea953a2a9e7ed3ffc0b4c0b649/service/src/main/java/gov/nasa/pds/api/engineering/elasticsearch/business/ProductBusinessObject.java#L91). These may or may not produce the same result but both are used by different endpoints. Should reduce the code to just a single method for LID -> LIDVID conversion then have all the endpoints use the same translation.

## 📜 To Reproduce
Code review

**Comment by tloubrieu-jpl** [comment]
closed by mistake

**Comment by jordanpadams** [comment]
@al-niessner @tloubrieu-jpl per our quick email discussion, the implementation may be inconsistent, but they both appear to work at the moment, so tabling this from this sprint.
