### ISSUE TITLE
the default proposed mime type in swagger-ui.html should be 'application/json'

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#88]
## 💪 Motivation
...so that I can get a structured response by default from the UI.

(currently it is application/csv because of alphabetical order I think)

## ⚖️ Acceptance Criteria
**Given** a deployed API (eg on http://localhost:8080/)
**When I perform** select an end-point , 
**Then I expect** the default proposed content type to be `application/json`, instead of `application/csv` on the screenshot 
![image](https://user-images.githubusercontent.com/60993872/152847919-b816ebf1-5968-43a9-bbef-265c96085e16.png)

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

The actual default is JSON. The display on swaggerhub has nothing to do what the Java does and not sure how order is defined by swaggerhub but it looks to be first typed first in list. However to get Object right, '*' needs to be first in the YAML. Again, we are constrained quite a bit by swagger.

**Comment by tloubrieu-jpl** [comment]
Now the default type is * and it return application/json, so I am considering this ticket as closed. See PR https://github.com/NASA-PDS/registry-api/pull/254
