### ISSUE TITLE
As a developer, I want to update in a single place the list of supported MIME types

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#9]
@tloubrieu-jpl commented on [Fri Aug 27 2021](https://github.com/NASA-PDS/registry-api-service/issues/65)

That should be handled as a constant in the MVC object (https://github.com/NASA-PDS/registry-api-service/blob/main/src/main/java/gov/nasa/pds/api/engineering/configuration/WebMVCConfig.java)

And used for example in:

- https://github.com/NASA-PDS/registry-api-service/blob/b52a93a7de20c017fcb93091a5e32c012d1d6470/src/main/java/gov/nasa/pds/api/engineering/controllers/MyBundlesApiController.java#L133
- https://github.com/NASA-PDS/registry-api-service/blob/b52a93a7de20c017fcb93091a5e32c012d1d6470/src/main/java/gov/nasa/pds/api/engineering/controllers/MyBundlesApiController.java#L165
- and in all the controllers

I believe we should have different caterogies of mime types for longProduct  or shortProduct descriptions since some format will be applicable for full product (pds4+json) or short product (json)

**Comment by tloubrieu-jpl** [comment]
@al-niessner do you think we still need to do something about that or did your latest work on the response format made that ticket obsolete ?

Thanks

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

I think you are as close to this as you are ever going to be unless you want to actually treat the single case a special case of the plural. Still, it would be 3 places to track supported MIME types:

1. swaggerhub at Plural/Singular -- reducing Plural/Singular to just Plural seems minimal but it would reduce the serialization support by half as well as halving the internal type management. Thus, collapsing to just Plural (means all returns have a Summary) would reduce current and future MIME support by 4x.
2. gov.nasa.pds.api.engineering.configuration.WebMVCCConfig for serialization
3. gov.nasa.pds.api.engineering.elasticsearch.business.RequestAndResponseContext for accept type to internal type mapping

**Comment by tloubrieu-jpl** [comment]
Thanks @al-niessner that sounds good, I am closing this ticket.
